// JohnO_fnc_randomItem.sqf

private ["_items"];

_items =
[

	"Exile_Item_EMRE",
	"Exile_Item_GloriousKnakworst",
	"Exile_Item_Surstromming",
	"Exile_Item_SausageGravy",
	"Exile_Item_Catfood",
	"Exile_Item_ChristmasTinner",
	"Exile_Item_BBQSandwich",
	"Exile_Item_MacasCheese",
	"Exile_Item_Dogfood",
	"Exile_Item_BeefParts",
	"Exile_Item_Cheathas",
	"Exile_Item_Noodles",
	"Exile_Item_SeedAstics",
	"Exile_Item_Raisins",
	"Exile_Item_Moobar",
	"Exile_Item_InstantCoffee",
	//drinks
	"Exile_Item_PlasticBottleCoffee",
	"Exile_Item_PowerDrink",
	"Exile_Item_PlasticBottleFreshWater",
	"Exile_Item_Beer",
	"Exile_Item_EnergyDrink",
	"Exile_Item_ChocolateMilk",
	"Exile_Item_MountainDupe",
	"Exile_Item_PlasticBottleEmpty",

	"BSF_WaterPure_Tabs",
	"BSF_WaterPure_Tabs",
	"BSF_Item_Vitamins1",
	"BSF_Item_Pain_Killlers",
	"BSF_Item_FirstAid_Kit1",
	"BSF_Item_Blood_Bag_Clean",
	"BSF_Item_Disinfectant_Spray",
	"BSF_IV_Bag",
	"BSF_Antibiotics",
	"BSF_Item_Blood_Bag_KR",
	"BSF_Item_IV_Bag_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Banndage_Used",
	"BSF_Item_Poison",
	"Exile_Item_InstaDoc",
	"Exile_Item_InstaDoc",
	"Exile_Item_InstaDoc",
	"Exile_Item_InstaDoc",

	// tools
	"BSF_Paint_Bucket_Green",
	"BSF_Paint_Bucket_Green",
	"BSF_Paint_Bucket_Green",
	"BSF_Paint_Bucket_Green",
	"BSF_Tarp_Blue",
	"BSF_Tarp_Blue",
	"BSF_Tarp_Blue",
	"BSF_Paintbrush",
	"BSF_Paintbrush",
	"BSF_Paintbrush",
	"BSF_Paintbrush",
	"BSF_Fishing_Net",
	"Exile_Item_Foolbox",
	"Exile_Item_Grinder",
	"Exile_Item_Hammer",
	"Exile_Item_Wrench",
	"Exile_Item_CarWheel",

	"Exile_Item_Rope",
	"Exile_Item_Rope",
	"Exile_Item_Rope",
	"Exile_Item_Rope",
	"Exile_Item_Defibrillator",
	"Exile_Item_Sand",
	"Exile_Item_Cement",
	"Exile_Item_Laptop",
	"Exile_Item_MetalWire",
	"Exile_Item_MetalWire",
	"Exile_Item_MetalWire",
	"Exile_Item_MetalWire",
	"Exile_Item_MetalWire",
	"Exile_Item_MetalWire",
	"Exile_Item_MetalScrews",
	"Exile_Item_MetalScrews",
	"Exile_Item_MetalScrews",
	"Exile_Item_MetalScrews",
	"Exile_Item_MetalScrews",
	"Exile_Item_MetalScrews",
	"Exile_Item_CodeLock",
	"Exile_Item_MetalPole",
	"Exile_Item_MetalPole",
	"Exile_Item_MetalPole",
	"Exile_Item_MetalBoard",
	"Exile_Item_MetalBoard",
	"Exile_Item_MetalBoard",
	"Exile_Item_LightBulb",
	"Exile_Item_LightBulb",
	"Exile_Item_LightBulb",
	"Exile_Item_ExtensionCord",
	"Exile_Item_ExtensionCord",
	"Exile_Item_ExtensionCord",
	"Exile_Item_DuctTape",
	"Exile_Item_DuctTape",
	"Exile_Item_DuctTape",
	"Exile_Item_FuelCanisterEmpty",
	"Exile_Item_JunkMetal",
	"Exile_Item_JunkMetal",
	"Exile_Item_JunkMetal",

	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_Matches",
	"Exile_Item_CanOpener",
	"Exile_Item_CanOpener",
	"Exile_Item_Handsaw",
	"Exile_Item_Pliers",
	// Junk
	"Exile_Item_Can_Empty",
	"Exile_Item_ToiletPaper",
	"Exile_Item_Can_Empty",
	"Exile_Item_ToiletPaper",
	"Exile_Item_Can_Empty",
	"Exile_Item_ToiletPaper"
];

_item = selectRandom _items;
_item