/*
* BSF_Server_Create_VehicleNameMap.sqf
* 
* BS-Free Game Servers
* www.bs-free.com
* © 2023 Troy - BS-Free
*
* This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. 
* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.
*/

VehicleNameMap = createHashMapFromArray [
["BSF_Offroad_Comms_Black_Matte","Offroad Comms, Black"], 
["BSF_Offroad_Comms_Black_Matte","Offroad Comms, Black"], 
["BSF_Cargo_Van_Black_Matte","Cargo Van, Matte Black"], 
["BSF_Gnat_01","BSF Gnat"], 
["BSF_B_Truck_01_mover_F","HEMTT Mover"], 
["BSF_B_Truck_01_box_F","HEMTT Box"], 
["BSF_B_Truck_01_ammo_F","HEMTT Ammo"], 
["BSF_B_Truck_01_repair_F","HEMTT Repair"], 
["BSF_B_Truck_01_fuel_F","HEMTT Fuel"], 
["OWP_MI26cg","Mi26"], 
["OWP_MI26ps","Mi26"], 
["OWP_MI26md","Mi26"], 
["OWP_MI26fl","Mi26"], 
["BSF_KTM50_Brown","KTM 50, Brown"], 
["BSF_KTM50_Black","KTM 50, Black"], 
["BSF_KTM50_Olive","KTM 50, Olive"], 
["BSF_KTM50_Sand","KTM 50, Sand"], 
["BSF_KTM50_Orange","KTM 50"], 
["BSF_KTM50_White","KTM 50"], 
["V12_KTM50CCN","KTM 50"], 
["V12_KTM50CCO","KTM 50"], 
["V12_KTM50CCB","KTM 50"], 
["BSF_YFZ450_QuadBike_Black","YFZ450 Quad, Black"], 
["BSF_YFZ450_QuadBike_Brown","YFZ450 Quad, Brown"], 
["BSF_YFZ450_QuadBike_Olive","YFZ450 Quad, Olive"], 
["BSF_YFZ450_QuadBike_Sand","YFZ450 Quad, Sand"], 
["V12_YFZ450_BLEU","YFZ450 Quad"], 
["V12_YFZ450_GRIS","YFZ450 Quad"], 
["V12_YFZ450_NOIR","YFZ450 Quad"], 
["V12_YFZ450_RACE1","YFZ450 Quad"], 
["V12_YFZ450_RACE2","YFZ450 Quad"], 
["V12_YFZ450_RACE3","YFZ450 Quad"], 
["V12_YFZ450_RACE4","YFZ450 Quad"], 
["V12_YFZ450_RACE5","YFZ450 Quad"], 
["V12_YFZ450_ROUGE","YFZ450 Quad"], 
["BSF_Aprilia_DirtBike_Black","Aprilia MXV 450, Black"], 
["BSF_Aprilia_DirtBike_Brown","Aprilia MXV 450, Brown"], 
["BSF_Aprilia_DirtBike_Olive","Aprilia MXV 450, Olive"], 
["BSF_Aprilia_DirtBike_Sand","Aprilia MXV 450, Sand"], 
["V12_APRILIAMXV450","Aprilia MXV 450"], 
["V12_APRILIAMXV4502","Aprilia MXV 450"], 
["V12_APRILIAMXV4503","Aprilia MXV 450"], 
["V12_APRILIAMXV4504","Aprilia MXV 450"], 
["V12_KTM","KTM 450 "], 
["BSF_MonkeyBike_Black","Monkey Bike, Black"], 
["BSF_MonkeyBike_Brown","Monkey Bike, Brown"], 
["BSF_MonkeyBike_Olive","Monkey Bike, Olive"], 
["BSF_MonkeyBike_Sand","Monkey Bike, Sand"], 
["BSF_MonkeyBike_Red","Monkey Bike, Red"], 
["V12_MONKEY_BC","Monkey Bike"], 
["V12_MONKEY_BrosserG","Monkey Bike"], 
["V12_MONKEY_BrosserD","Monkey Bike"], 
["V12_MONKEY_MAT","Monkey Bike"], 
["V12_MONKEY_noir","Monkey Bike"], 
["V12_MONKEY_OR","Monkey Bike"], 
["V12_MONKEY_Rouge","Monkey Bike"], 
["V12_MONKEY_VO","Monkey Bike"], 
["Exile_Bike_OldBike ","Old Bike"], 
["Exile_Bike_MountainBike ","Mountain Bike"], 
["Exile_Bike_QuadBike_Black","Quad Bike Black"], 
["Exile_Bike_QuadBike_Blue","Quad Bike Blue"], 
["Exile_Bike_QuadBike_Red","Quad Bike Red"], 
["Exile_Bike_QuadBike_White","Quad BikeWhite"], 
["Exile_Bike_QuadBike_Nato","Quad Bike Nato"], 
["Exile_Bike_QuadBike_Csat","Quad Bike CSAT"], 
["Exile_Bike_QuadBike_Fia","Quad Bike FIA"], 
["Exile_Bike_QuadBike_Guerilla01","Quad Bike Guerilla 01"], 
["Exile_Bike_QuadBike_Guerilla02","Quad Bike Guerilla 02"], 
["B_G_Quadbike_01_F","Quad Bike"], 
["B_Quadbike_01_F","Quad Bike"], 
["O_G_Quadbike_01_F","Quad Bike"], 
["O_Quadbike_01_F","Quad Bike"], 
["I_Quadbike_01_F","Quad Bike"], 
["I_G_Quadbike_01_F","Quad Bike"], 
["C_Quadbike_01_F","Quad Bike"], 
["O_T_Quadbike_01_ghex_F","Quad Bike Green Hex"], 
["I_E_Quadbike_01_F","Quad Bike"], 
["Exile_Car_Kart_BluKing","Kart Blue King"], 
["Exile_Car_Kart_RedStone","Kart Red Stone"], 
["Exile_Car_Kart_Vrana","Kart "], 
["Exile_Car_Kart_Green","Kart Green"], 
["Exile_Car_Kart_Blue","Kart Blue"], 
["Exile_Car_Kart_Orange","Kart Orange"], 
["Exile_Car_Kart_White","Kart White"], 
["Exile_Car_Kart_Yellow","Kart Yellow"], 
["Exile_Car_Kart_Black","Kart Black"], 
["B_UAV_01_F","AR-2 Darter"], 
["B_UAV_02_F","MQ-4A Greyhawk"], 
["B_UAV_02_CAS_F","MQ-4A Greyhawk (CAS)"], 
["B_UGV_01_F","UGV Stomper"], 
["B_UGV_01_rcws_F","UGV Stomper RCWS"], 
["O_UAV_01_F","Tayran AR-2"], 
["O_UAV_02_F","K40 Ababil-3"], 
["O_UAV_02_CAS_F","K40 Ababil-3(CAS)"], 
["O_UGV_01_F","UGV Saif"], 
["O_UGV_01_rcws_F","UGV Saif RCWF"], 
["I_UAV_01_F","AR-2 Darter"], 
["I_UAV_02_F","K40 Ababil-3"], 
["I_UAV_02_CAS_F","K40 Ababil-3(CAS)"], 
["I_UGV_01_F","UGV Stomper"], 
["I_UGV_01_rcws_F","UGV Stomper RCWS"], 
["B_T_UAV_03_F","MQ-12 Falcon"], 
["O_T_UAV_04_CAS_F","KH-3A Fenghuang"], 
["I_UavTerminal","UAV Terminal"], 
["I_E_UavTerminal","UAV Terminal"], 
["I_UAV_01_backpack_F","UAV Backpack"], 
["I_E_UAV_01_backpack_F","UAV Backpack"], 
["Exile_Car_Hatchback_Beige","Hatchback Beige"], 
["Exile_Car_Hatchback_Green","Hatchback Green"], 
["Exile_Car_Hatchback_Blue","Hatchback Blue"], 
["Exile_Car_Hatchback_BlueCustom","Hatchback Blue Custom"], 
["Exile_Car_Hatchback_BeigeCustom","Hatchback Beige Custom"], 
["Exile_Car_Hatchback_Yellow","Hatchback Yellow"], 
["Exile_Car_Hatchback_Grey","Hatchback Grey"], 
["Exile_Car_Hatchback_Black","Hatchback Black"], 
["Exile_Car_Hatchback_Dark","Hatchback Dark"], 
["Exile_Car_Hatchback_Rusty1","Hatchback Rusty 01"], 
["Exile_Car_Hatchback_Rusty2","Hatchback Rusty 02"], 
["Exile_Car_Hatchback_Rusty3","Hatchback Rusty 03"], 
["Exile_Car_Hatchback_Sport_Red","Hatchback Sport Red"], 
["Exile_Car_Hatchback_Sport_Blue","Hatchback Sport Blue"], 
["Exile_Car_Hatchback_Sport_Orange","Hatchback Sport Orange"], 
["Exile_Car_Hatchback_Sport_White","Hatchback Sport White"], 
["Exile_Car_Hatchback_Sport_Beige","Hatchback Sport Beige"], 
["Exile_Car_Hatchback_Sport_Green","Hatchback Sport Green"], 
["Exile_Car_Golf_Red","Golf Red"], 
["Exile_Car_Golf_Black","Golf Black"], 
["Exile_Car_Octavius_White","Octavius White"], 
["Exile_Car_Octavius_Black","Octavious Black"], 
["Exile_Car_SUV_Red","SUV Red"], 
["Exile_Car_SUV_Black","SUV Black"], 
["Exile_Car_SUV_Grey","SUV Grey"], 
["Exile_Car_SUV_Orange","SUV Orange"], 
["Exile_Car_SUV_Rusty1","SUV Rusty 1"], 
["Exile_Car_SUV_Rusty2","SUV Rusty 2"], 
["Exile_Car_SUV_Rusty3","SUV Rusty 3"], 
["Exile_Car_Lada_Green","Lada Green"], 
["Exile_Car_Lada_Taxi","Lada Taxi"], 
["Exile_Car_Lada_Red","Lada Red"], 
["Exile_Car_Lada_White","Lada White"], 
["Exile_Car_Lada_Hipster","Lada Hipster"], 
["Lada_Militia","Lada Military"], 
["Lada_Civ_01","Lada Civillian 01"], 
["Lada_Civ_02","Lada Civillian 02"], 
["Lada_Civ_03","Lada Civillian 03"], 
["Lada_Civ_04","Lada Civillian 04"], 
["Exile_Car_Volha_Blue","Volha Blue"], 
["Exile_Car_Volha_White","Volha White"], 
["Exile_Car_Volha_Black","Volha Black"], 
["Exile_Car_SUVXL_Black","SUV XL Black"], 
["Exile_Car_SUV_Armed_Black","SUV Armed Black"], 
["SUV_civ_01","SUV Civillian 01"], 
["SUV_civ_02","SUV Civillian 02"], 
["SUV_civ_03","SUV Civillian 03"], 
["SUV_civ_04","SUV Civillian 04"], 
["Exile_Car_Ikarus_Blue","Ikarus Blue"], 
["Exile_Car_Ikarus_Red","Ikarus Red"], 
["Exile_Car_Ikarus_Party","Ikarus Party"], 
["Ikarus_Govnodav_02","Ikarus Govnodav 02"], 
["Ikarus_Govnodav_01","Ikarus Govnodav 01"], 
["Ikarus_Civ_02","Ikarus Civillian 02"], 
["Exile_Car_Ural_Open_Blue","URAL Blue"], 
["Exile_Car_Ural_Open_Yellow","URAL Yellow"], 
["Exile_Car_Ural_Open_Worker","URAL Worker"], 
["Exile_Car_Ural_Open_Military","URAL Military"], 
["Exile_Car_Ural_Covered_Blue","URAL Covered Blue"], 
["Exile_Car_Ural_Covered_Yellow","URAL Covered Yellow"], 
["Exile_Car_Ural_Covered_Worker","URAL Covered Worker"], 
["Exile_Car_Ural_Covered_Military","URAL Covered Military"], 
["Exile_Car_V3S_Open","V3S Truck Open"], 
["Exile_Car_V3S_Covered","V3S Truck Covered"], 
["C_Tractor_01_F","Tractor"], 
["Exile_Car_Tractor_Red","Tractor Red"], 
["TractorOld","Old Tractor"], 
["Exile_Car_OldTractor_Red","Old Tractor Red"], 
["TowingTractor","Tractor Towing"], 
["Exile_Car_TowTractor_White","Tractor Towing White"], 
["Exile_Car_UAZ_Green","UAZ Green"], 
["Exile_Car_UAZ_Open_Green","UAZ Open Green"], 
["Exile_Car_LandRover_Red","Landrover Red"], 
["Exile_Car_LandRover_Urban","Landrover Urban"], 
["Exile_Car_LandRover_Green","Landrover Green"], 
["Exile_Car_LandRover_Sand","Landrover Sand"], 
["Exile_Car_LandRover_Desert","Landrover Desert"], 
["Exile_Car_LandRover_Ambulance_Green","Landrover Ambulance Green"], 
["Exile_Car_LandRover_Ambulance_Desert","Landrover Ambulance Desert"], 
["Exile_Car_LandRover_Ambulance_Sand","Landrover Ambulance Sand"], 
["C_IDAP_Offroad_01_F","IDAP Offroad"], 
["Exile_Car_Offroad_Red","Offroad Red"], 
["Exile_Car_Offroad_Beige","Offroad Beige"], 
["Exile_Car_Offroad_White","Offroad White"], 
["Exile_Car_Offroad_Blue","Offroad Blue"], 
["Exile_Car_Offroad_DarkRed","Offroad Dark Red"], 
["Exile_Car_Offroad_BlueCustom","Offroad Custom Blue"], 
["Exile_Car_Offroad_Guerilla01","Offroad Guerilla 01"], 
["Exile_Car_Offroad_Guerilla02","Offroad Guerilla 02"], 
["Exile_Car_Offroad_Guerilla03","Offroad Guerilla 03"], 
["Exile_Car_Offroad_Guerilla04","Offroad Guerilla 04"], 
["Exile_Car_Offroad_Guerilla05","Offroad Guerilla 05"], 
["Exile_Car_Offroad_Guerilla06","Offroad Guerilla 06"], 
["Exile_Car_Offroad_Guerilla07","Offroad Guerilla 07"], 
["Exile_Car_Offroad_Guerilla08","Offroad Guerilla 08"], 
["Exile_Car_Offroad_Guerilla09","Offroad Guerilla 09"], 
["Exile_Car_Offroad_Guerilla10","Offroad Guerilla 10"], 
["Exile_Car_Offroad_Guerilla11","Offroad Guerilla 11"], 
["Exile_Car_Offroad_Guerilla12","Offroad Guerilla 12"], 
["Exile_Car_Offroad_Rusty1","Offroad Rusty 1"], 
["Exile_Car_Offroad_Rusty2","Offroad Rusty 2"], 
["Exile_Car_Offroad_Rusty3","Offroad Rusty 3"], 
["C_Offroad_02_unarmed_black_F","Offroad Unarmed Black"], 
["C_Offroad_02_unarmed_blue_F","Offroad Unarmed Blue"], 
["C_Offroad_02_unarmed_green_F","Offroad Unarmed Green"], 
["C_Offroad_02_unarmed_orange_F","Offroad Unarmed Orange"], 
["C_Offroad_02_unarmed_red_F","Offroad Unarmed Red"], 
["C_Offroad_02_unarmed_white_F","Offroad Unarmed White"], 
["I_C_Offroad_02_unarmed_brown_F","Offroad Unarmed Brown"], 
["I_C_Offroad_02_unarmed_olive_F","Offroad Unarmed Olive"], 
["B_G_Offroad_01_F","Offroad"], 
["O_G_Offroad_01_F","Offroad"], 
["I_G_Offroad_01_F","Offroad"], 
["I_E_Offroad_01_F","Offroad"], 
["C_Offroad_01_repair_F","Offroad Repair"], 
["B_GEN_Offroad_01_gen_F","Offroad Gen"], 
["B_GEN_Offroad_01_comms_F","Offroad Comms"], 
["B_GEN_Offroad_01_covered_F","Offroad Covered"], 
["C_Offroad_01_comms_F","Offroad Comms"], 
["C_Offroad_01_covered_F","Offroad Covered"], 
["I_E_Offroad_01_comms_F","Offroad Comms"], 
["I_E_Offroad_01_covered_F","Offroad, Covered, Camo"], 
["Exile_Car_Offroad_Armed_Guerilla01","Offroad Armed Guerilla 01"], 
["Exile_Car_Offroad_Armed_Guerilla02","Offroad Armed Guerilla 02"], 
["Exile_Car_Offroad_Armed_Guerilla03","Offroad Armed Guerilla 03"], 
["Exile_Car_Offroad_Armed_Guerilla04","Offroad Armed Guerilla 04"], 
["Exile_Car_Offroad_Armed_Guerilla05","Offroad Armed Guerilla 05"], 
["Exile_Car_Offroad_Armed_Guerilla06","Offroad Armed Guerilla 06"], 
["Exile_Car_Offroad_Armed_Guerilla07","Offroad Armed Guerilla 07"], 
["Exile_Car_Offroad_Armed_Guerilla08","Offroad Armed Guerilla 08"], 
["Exile_Car_Offroad_Armed_Guerilla09","Offroad Armed Guerilla 09"], 
["Exile_Car_Offroad_Armed_Guerilla10","Offroad Armed Guerilla 10"], 
["Exile_Car_Offroad_Armed_Guerilla11","Offroad Armed Guerilla 11"], 
["Exile_Car_Offroad_Armed_Guerilla12","Offroad Armed Guerilla 12"], 
["B_G_Offroad_01_armed_F","Offroad Armed"], 
["O_G_Offroad_01_armed_F","Offroad Armed"], 
["I_G_Offroad_01_armed_F","Offroad Armed"], 
["Exile_Car_Offroad_Repair_Civillian","Offroad Repair Civillian"], 
["Exile_Car_Offroad_Repair_Red","Offroad Repair Red"], 
["Exile_Car_Offroad_Repair_Beige","Offroad Repair Beige"], 
["Exile_Car_Offroad_Repair_White","Offroad Repair White"], 
["Exile_Car_Offroad_Repair_Blue","Offroad Repair Blue"], 
["Exile_Car_Offroad_Repair_DarkRed","Offroad Repair Dark Red"], 
["Exile_Car_Offroad_Repair_BlueCustom","Offroad Repair Blue Custom"], 
["Exile_Car_Offroad_Repair_Guerilla01","Offroad Repair Guerilla 01"], 
["Exile_Car_Offroad_Repair_Guerilla02","Offroad Repair Guerilla 02"], 
["Exile_Car_Offroad_Repair_Guerilla03","Offroad Repair Guerilla 03"], 
["Exile_Car_Offroad_Repair_Guerilla04","Offroad Repair Guerilla 04"], 
["Exile_Car_Offroad_Repair_Guerilla05","Offroad Repair Guerilla 05"], 
["Exile_Car_Offroad_Repair_Guerilla06","Offroad Repair Guerilla 06"], 
["Exile_Car_Offroad_Repair_Guerilla07","Offroad Repair Guerilla 07"], 
["Exile_Car_Offroad_Repair_Guerilla08","Offroad Repair Guerilla 08"], 
["Exile_Car_Offroad_Repair_Guerilla09","Offroad Repair Guerilla 09"], 
["Exile_Car_Offroad_Repair_Guerilla10","Offroad Repair Guerilla 10"], 
["Exile_Car_Offroad_Repair_Guerilla11","Offroad Repair Guerilla 11"], 
["B_G_Offroad_01_repair_F","Offroad Repair"], 
["O_G_Offroad_01_repair_F","Offroad Repair"], 
["Exile_Car_Van_Black","Van Black"], 
["Exile_Car_Van_White","Van White"], 
["Exile_Car_Van_Red","Van Red"], 
["Exile_Car_Van_Guerilla01","Van Guerilla 01"], 
["Exile_Car_Van_Guerilla02","Van Guerilla 02"], 
["Exile_Car_Van_Guerilla03","Van Guerilla 03"], 
["Exile_Car_Van_Guerilla04","Van Guerilla 04"], 
["Exile_Car_Van_Guerilla05","Van Guerilla 05"], 
["Exile_Car_Van_Guerilla06","Van Guerilla 06"], 
["Exile_Car_Van_Guerilla07","Van Guerilla 07"], 
["Exile_Car_Van_Guerilla08","Van Guerilla 08"], 
["B_G_Van_01_transport_F","Truck"], 
["O_G_Van_01_transport_F","Truck"], 
["I_G_Van_01_transport_F","Truck"], 
["C_Van_01_transport_F","Truck"], 
["C_Van_01_transport_red_F","Truck Red"], 
["C_Van_01_transport_white_F","Truck White"], 
["I_C_Van_01_transport_F","Truck"], 
["I_C_Van_01_transport_brown_F","Truck Brown"], 
["I_C_Van_01_transport_olive_F","Truck Olive"], 
["B_G_Van_02_vehicle_F","Cargo Van"], 
["B_GEN_Van_02_vehicle_F","Cargo Van"], 
["O_G_Van_02_vehicle_F","Cargo Van"], 
["I_G_Van_02_vehicle_F","Cargo Van"], 
["I_C_Van_02_vehicle_F","Cargo Van"], 
["C_Van_02_vehicle_F","Cargo Van"], 
["C_IDAP_Van_02_vehicle_F","Cargo Van"], 
["C_Van_02_medevac_F","Cargo Van Medivac"], 
["C_IDAP_Van_02_medevac_F","Cargo Van Medivac"], 
["B_G_Van_02_transport_F","Cargo Van Transport"], 
["B_GEN_Van_02_transport_F","Cargo Van Transport"], 
["O_G_Van_02_transport_F","Cargo Van Transport"], 
["I_G_Van_02_transport_F","Cargo Van Transport"], 
["I_C_Van_02_transport_F ","Cargo Van Transport"], 
["C_Van_02_transport_F","Cargo Van Transport"], 
["C_IDAP_Van_02_transport_F","Cargo Van Transport"], 
["C_Van_02_service_F","Cargo Van Service"], 
["I_E_Van_02_vehicle_F ","Cargo Van"], 
["I_E_Van_02_transport_F ","Cargo Van Transport"], 
["I_E_Van_02_medevac_F ","Cargo Van Medivac"], 
["I_E_Van_02_transport_MP_F ","Cargo Van Transport"], 
["Exile_Car_Van_Box_Black","Box Van black"], 
["Exile_Car_Van_Box_White","Box Van White"], 
["Exile_Car_Van_Box_Red","Box Van Red"], 
["Exile_Car_Van_Box_Guerilla01","Guerilla 01"], 
["Exile_Car_Van_Box_Guerilla02","Guerilla 02"], 
["Exile_Car_Van_Box_Guerilla03","Guerilla 03"], 
["Exile_Car_Van_Box_Guerilla04","Guerilla 04"], 
["Exile_Car_Van_Box_Guerilla05","Guerilla 05"], 
["Exile_Car_Van_Box_Guerilla06","Guerilla 06"], 
["Exile_Car_Van_Box_Guerilla07","Guerilla 07"], 
["Exile_Car_Van_Box_Guerilla08","Guerilla 08"], 
["C_Van_01_box_F","Box Van"], 
["C_Van_01_box_red_F","Box Van Red"], 
["C_Van_01_box_white_F","Box Van White"], 
["Exile_Car_Van_Fuel_Black","Fuel Van Black"], 
["Exile_Car_Van_Fuel_White","Fuel Van White"], 
["Exile_Car_Van_Fuel_Red","Fuel Van Red"], 
["Exile_Car_Van_Fuel_Guerilla01","Fuel Van Guerilla 01"], 
["Exile_Car_Van_Fuel_Guerilla02","Fuel Van Guerilla 02"], 
["Exile_Car_Van_Fuel_Guerilla03","Fuel Van Guerilla 03"], 
["B_G_Van_01_fuel_F","Fuel Van"], 
["O_G_Van_01_fuel_F","Fuel Van"], 
["I_G_Van_01_fuel_F","Fuel Van"], 
["C_Van_01_fuel_F","Fuel Van"], 
["C_Van_01_fuel_red_F","Fuel Van Red"], 
["C_Van_01_fuel_white_F","Fuel Van White"], 
["C_Offroad_02_unarmed_F","Offroad unarmed"], 
["I_C_Offroad_02_unarmed_F","Offroad unarmed"], 
["Exile_Car_MB4WD","MB4 Woodland"], 
["Exile_Car_MB4WDOpen","MB4 Open"], 
["C_IDAP_Offroad_02_unarmed_F","IDAP Offroad"], 
["Exile_Car_HMMWV_MEV_Green","Humvee Green"], 
["Exile_Car_HMMWV_MEV_Desert","Humvee Desert"], 
["Exile_Car_HMMWV_UNA_Green","Humvee Unarmed Green"], 
["Exile_Car_HMMWV_UNA_Desert","Humvee Unarmed Desert"], 
["Exile_Car_HMMWV_M2_Green","Humvee M2 Green"], 
["Exile_Car_HMMWV_M2_Desert","Humvee M2 Desert"], 
["Exile_Car_HMMWV_M134_Green","Humvee M134 Green"], 
["Exile_Car_HMMWV_M134_Desert","Humvee M134 Desert "], 
["HMMWV_UNA_des","Humvee Unarmed Desert"], 
["HMMWV_UNA","Humvee Unarmed"], 
["HMMWV_MEV_des","Humvee MEV Desert"], 
["HMMWV_MEV","Humvee MEV Desert"], 
["HMMWV_M2_des ","Humvee M2 Desert"], 
["HMMWV_M2","Humvee M2 Desert"], 
["HMMWV_M134_des","Humvee M134 Desert"], 
["HMMWV_M134","Humvee M134 Desert"], 
["HMMWV_M2_GPK_1","Humvee M2 GPK"], 
["HMMWV_M2_GPK_Base","Humvee M2 GPK"], 
["O_T_LSV_02_unarmed_F","Quilin Unarmed"], 
["O_T_LSV_02_unarmed_viper_F","Quilin Unarmed Viper"], 
["O_LSV_02_unarmed_F","Quilin Unarmed"], 
["O_LSV_02_unarmed_viper_F","Quilin Unarmed Viper"], 
["O_T_LSV_02_unarmed_black_F","Quilin Unarmed Black"], 
["O_T_LSV_02_unarmed_ghex_F","Quilin Unarmed Green Hex"], 
["O_T_LSV_02_unarmed_arid_F","Quilin Unarmed"], 
["O_LSV_02_unarmed_black_F","Quilin Unarmed Black"], 
["O_LSV_02_unarmed_ghex_F","Quilin Unarmed Green Hex"], 
["O_LSV_02_unarmed_arid_F","Quilin Unarmed Arid"], 
["Exile_Car_QilinUnarmed","Quilin Unarmed"], 
["O_T_LSV_02_armed_F","Quilin Armed"], 
["O_T_LSV_02_armed_viper_F","Quilin Armed Viper"], 
["O_LSV_02_armed_F","Quilin Armed"], 
["O_LSV_02_armed_viper_F","Quilin Armed Viper"], 
["O_T_LSV_02_armed_black_F","Quilin Armed Black"], 
["O_T_LSV_02_armed_ghex_F","Quilin Armed Green Hex"], 
["O_T_LSV_02_armed_arid_F","Quilin Armed Arid"], 
["O_LSV_02_armed_black_F","Quilin Armed Black"], 
["O_LSV_02_armed_ghex_F","Quilin Armed Green Hex"], 
["O_LSV_02_armed_arid_F","Quilin Armed"], 
["O_LSV_02_AT_F","Quilin Armed Anti Tank"], 
["O_T_LSV_02_AT_F","Quilin Armed Anti Tank"], 
["B_CTRG_LSV_01_light_F","Prowler Unarmed Light"], 
["B_LSV_01_unarmed_F","Prowler Unarmed"], 
["B_LSV_01_unarmed_black_F","Prowler Unarmed Black"], 
["B_LSV_01_unarmed_olive_F","Prowler Unarmed Olive"], 
["B_LSV_01_unarmed_sand_F","Prowler Unarmed Sand"], 
["B_T_LSV_01_unarmed_F","Prowler Unarmed"], 
["B_T_LSV_01_unarmed_black_F","Prowler Unarmed Black"], 
["B_T_LSV_01_unarmed_olive_F","Prowler Unarmed Olive"], 
["B_T_LSV_01_unarmed_sand_F","Prowler Unarmed Sand"], 
["B_T_LSV_01_unarmed_CTRG_F","Prowler Unarmed"], 
["Exile_Car_ProwlerUnarmed","Prowler Unarmed"], 
["Exile_Car_ProwlerLight","Prowler Unarmed Light"], 
["B_LSV_01_armed_F","Prowler Armed"], 
["B_LSV_01_armed_black_F","Prowler Armed Black"], 
["B_LSV_01_armed_olive_F","Prowler Armed Olive"], 
["B_LSV_01_armed_sand_F","Prowler Armed Sand"], 
["B_T_LSV_01_armed_F","Prowler Armed"], 
["B_T_LSV_01_armed_black_F","Prowler Armed Black"], 
["B_T_LSV_01_armed_olive_F","Prowler Armed Olive"], 
["B_T_LSV_01_armed_sand_F","Prowler Armed Sand"], 
["B_T_LSV_01_armed_CTRG_F","Prowler Armed"], 
["B_T_LSV_01_AT_F","Prowler Armed Anti Tank"], 
["B_LSV_01_AT_F","Prowler Armed Anti Tank"], 
["Exile_Car_Hunter","Hunter"], 
["B_T_MRAP_01_F","Hunter"], 
["B_MRAP_01_F","Hunter"], 
["B_MRAP_01_hmg_F","Hunter HMG"], 
["B_MRAP_01_gmg_F","Hunter GMG"], 
["Exile_Car_Ifrit","Ifrit"], 
["O_MRAP_02_F","Ifrit"], 
["O_MRAP_02_hmg_F","Ifrit HMG"], 
["O_MRAP_02_gmg_F","Ifrit GMG"], 
["Exile_Car_Strider","Strider"], 
["I_MRAP_03_F","Strider"], 
["I_MRAP_03_hmg_F","Strider HMG"], 
["I_MRAP_03_gmg_F","Strider GMG"], 
["Exile_Car_HEMMT","HEMMT"], 
["B_Truck_01_transport_F","HEMMT Transport"], 
["B_T_Truck_01_transport_F","HEMMT Transport"], 
["B_Truck_01_covered_F","HEMMT Covered"], 
["B_T_Truck_01_covered_F","HEMMT Covered"], 
["B_Truck_01_mover_F","HEMMT Mover"], 
["B_T_Truck_01_mover_F","HEMMT Mover"], 
["B_Truck_01_box_F","HEMMT Box"], 
["B_T_Truck_01_box_F","HEMMT Box"], 
["B_Truck_01_Repair_F","HEMMT Repair"], 
["B_T_Truck_01_Repair_F","HEMMT Repair"], 
["B_Truck_01_ammo_F","HEMMT Ammo"], 
["B_T_Truck_01_ammo_F","HEMMT Ammo"], 
["B_Truck_01_fuel_F","HEMMT Fuel"], 
["B_T_Truck_01_fuel_F","HEMMT Fuel"], 
["B_Truck_01_medical_F","HEMMT Medical"], 
["B_T_Truck_01_medical_F","HEMMT Medical"], 
["B_Truck_01_cargo_F","HEMMT Cargo"], 
["B_T_Truck_01_cargo_F","HEMMT Cargo"], 
["B_Truck_01_flatbed_F","HEMMT Flatbed"], 
["B_T_Truck_01_flatbed_F","HEMMT Flatbed"], 
["Exile_Car_Zamak","Zamak"], 
["O_Truck_02_covered_F","Zamak Covered"], 
["O_Truck_02_transport_F","Zamak Transport"], 
["O_Truck_02_box_F","Zamak Box"], 
["O_Truck_02_medical_F","Zamak Medical"], 
["O_Truck_02_Ammo_F","Zamak Ammo"], 
["O_Truck_02_fuel_F","Zamak Fuel"], 
["I_Truck_02_transport_F","Zamak Transport"], 
["I_Truck_02_ammo_F","Zamak Ammo"], 
["I_Truck_02_box_F","Zamak Box"], 
["I_Truck_02_medical_F","Zamak Medical"], 
["I_Truck_02_fuel_F","Zamak Fuel"], 
["C_IDAP_Truck_02_F","IDAP Zamak"], 
["C_IDAP_Truck_02_transport_F","IDAP Zamak Transport"], 
["C_IDAP_Truck_02_water_F","IDAP Zamak Water"], 
["I_E_Truck_02_Ammo_F","Zamak Ammo"], 
["I_E_Truck_02_fuel_F","Zamak Fuel"], 
["I_E_Truck_02_Medical_F","Zamak Medical"], 
["I_E_Truck_02_Box_F","Zamak Box"], 
["I_E_Truck_02_transport_F","Zamak Transport"], 
["I_E_Truck_02_F","Zamak"], 
["Exile_Car_Tempest","Tempest"], 
["O_T_Truck_03_transport_ghex_F","Tempest Transport Green Hex"], 
["O_T_Truck_03_covered_ghex_F","Tempest Covered Green Hex"], 
["O_T_Truck_03_device_ghex_F","Tempest Device Green Hex"], 
["O_Truck_03_transport_F","Tempest Transport "], 
["O_Truck_03_covered_F","Tempest Covered "], 
["O_Truck_03_repair_F","Tempest Repair"], 
["O_Truck_03_ammo_F","Tempest Ammo"], 
["O_Truck_03_fuel_F","Tempest Fuel"], 
["O_Truck_03_medical_F","Tempest Medical"], 
["O_Truck_03_device_F","Tempest Device"], 
["B_T_APC_Wheeled_01_cannon_F","AMV-7 Marshall"], 
["B_APC_Wheeled_01_cannon_F","AMV-7 Marshall"], 
["B_APC_Wheeled_03_cannon_F","AFV-4 Gorgon"], 
["I_APC_Wheeled_03_cannon_F","FV-720 Mora"], 
["B_APC_Wheeled_03_cannon_F","AFV-4 Gorgon"], 
["O_APC_Wheeled_02_rcws_F","MSE-3 Madrid"], 
["O_APC_Wheeled_02_rcws_v2_F","MSE-3 Madrid V2"], 
["O_T_APC_Wheeled_02_rcws_ghex_F","MSE-3 Madrid RCWS"], 
["O_T_APC_Wheeled_02_rcws_v2_ghex_F","MSE-3 Madrid RCWS V2"], 
["O_APC_Tracked_02_cannon_F","BTR Kamysh"], 
["O_T_APC_Tracked_02_cannon_ghex_F","BTR-K Kamysh GHex"], 
["","ARMA / Exile"], 
["I_APC_tracked_03_cannon_F","FV-720 Mora"], 
["I_E_APC_tracked_03_cannon_F","Armored Personal Carrier Armed"], 
["B_APC_Tracked_01_AA_F","IFV-6a Cheetah"], 
["B_T_APC_Tracked_01_AA_F","IFV-6a Cheetah AA"], 
["B_APC_Tracked_01_rcws_F","IFV-6c Panther"], 
["B_T_APC_Tracked_01_rcws_F","IFV-6c Panther RCWS"], 
["O_APC_Tracked_02_AA_F","ZSU-39 Tigris"], 
["O_T_APC_Tracked_02_AA_ghex_F","ZSU-39 Tigris Green Hex"], 
["B_APC_Tracked_01_CRV_F","CRV-6e Bobcat"], 
["B_T_APC_Tracked_01_CRV_F","CRV-6e Bobcat"], 
["B_MBT_01_cannon_F","M2A1 Slammer"], 
["B_MBT_01_arty_F","M4 Scorcher"], 
["B_MBT_01_mlrs_F","M5 Sandstorm MLRS"], 
["B_MBT_01_TUSK_F","M2A4 Slammer UP"], 
["O_MBT_02_cannon_F","T-100 Varsuk"], 
["O_MBT_02_arty_F","2S9 Sochor"], 
["I_MBT_03_cannon_F","MBT-52 Kuma"], 
["O_MBT_04_cannon_F","T-140K Angara"], 
["O_T_MBT_04_cannon_F","T-140K Angara"], 
["O_MBT_04_command_F","T-140K Angara Command"], 
["O_T_MBT_04_command_F","T-140K Angara Command"], 
["B_AFV_Wheeled_01_cannon_F","Rhino MGS"], 
["B_T_AFV_Wheeled_01_cannon_F","Rhino MGS"], 
["B_AFV_Wheeled_01_up_cannon_F","Rhino MGS UP"], 
["B_T_AFV_Wheeled_01_up_cannon_F","Rhino MGS UP"], 
["I_LT_01_scout_F","AWC 303 Nyx Recon"], 
["I_LT_01_cannon_F","AWC 304 Nyx Autocannon"], 
["I_LT_01_AA_F","AWC 302 Nyx Anti Air"], 
["I_LT_01_AT_F","AWC 302 Nyx Anti Tank"], 
["Exile_Car_BRDM2_HQ","BRDM2 Command"], 
["Exile_Car_BTR40_MG_Green","BTR -40 Minigun Green"], 
["Exile_Car_BTR40_MG_Camo","BTR -40 Minigun Camo"], 
["Exile_Car_BTR40_Green","BTR -40  Green"], 
["Exile_Car_BTR40_Camo","BTR -40 Camo"], 
["Exile_Chopper_Hummingbird_Green","Hummingbird"], 
["B_Heli_Light_01_F","Hummingbird"], 
["B_Heli_Light_01_stripped_F","Hummingbird"], 
["Exile_Chopper_Hummingbird_Civillian_Blue","Hummingbird Blue Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Red","Hummingbird Red Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_ION","Hummingbird ION Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_BlueLine","Hummingbird Blue Line Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Digital","Hummingbird Digital Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Elliptical","Hummingbird Elliptical Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Furious","Hummingbird Furious Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_GrayWatcher","Hummingbird Gray Watcher Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Jeans","Hummingbird Jeans Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Light","Hummingbird Light Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Shadow","Hummingbird Shadow Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Sheriff","Hummingbird Sheriff Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Speedy","Hummingbird Speedy Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Sunset","Hummingbird Sunset Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Vrana","Hummingbird Vrana Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Wasp","Hummingbird Wasp Civillian"], 
["Exile_Chopper_Hummingbird_Civillian_Wave","Hummingbird Wave Civillian"], 
["I_C_Heli_Light_01_civil_F","Hummingbird"], 
["B_Heli_Light_01_armed_F","AH-9 Pawnee"], 
["Exile_Chopper_Huey_Green","Huey Green"], 
["Exile_Chopper_Huey_Desert","Huey Desert"], 
["Exile_Chopper_Huey_Armed_Green","Huey Armed Green"], 
["Exile_Chopper_Huey_Armed_Desert","Huey Armed Desert"], 
["Exile_Chopper_Orca_CSAT","Orca CSAT"], 
["Exile_Chopper_Orca_Black","Orca Black"], 
["Exile_Chopper_Orca_BlackCustom","Orca Black Custom"], 
["O_Heli_Light_02_unarmed_F","Orca Unarmed"], 
["O_Heli_Light_02_F","Orca Armed"], 
["O_Heli_Light_02_v2_F","Orca Armed V2"], 
["O_Heli_Light_02_dynamicLoadout_F","Orca Armed Dynamic Loadout"], 
["Exile_Chopper_Hellcat_Green","WY-55 Hellcat Green"], 
["Exile_Chopper_Hellcat_FIA","WY-55 Hellcat Unarmed"], 
["I_Heli_light_03_unarmed_F","WY-55 Hellcat Unarmed"], 
["I_E_Heli_light_03_unarmed_F","WY-55 Hellcat Unarmed"], 
["I_Heli_light_03_F","WY-55 Hellcat Armed"], 
["I_Heli_light_03_dynamicLoadout_F","WY-55 Hellcat Dynamic Loadout"], 
["I_E_Heli_light_03_dynamicLoadout_F","WY-55 Hellcat Dynamic Loadout"], 
["Exile_Chopper_Mohawk_FIA","Mohawk"], 
["I_Heli_Transport_02_F","Mohawk Transport"], 
["Exile_Chopper_Huron_Black","Huron Black"], 
["Exile_Chopper_Huron_Green","Huron Green"], 
["B_Heli_Transport_03_unarmed_F","Huron Black"], 
["B_Heli_Transport_03_unarmed_green_F","Huron Green "], 
["B_Heli_Transport_03_F","Huron Armed"], 
["B_Heli_Transport_03_black_F","Huron Armed Black"], 
["Exile_Chopper_Taru_Transport_CSAT","Taru Transport CSAT"], 
["Exile_Chopper_Taru_Transport_Black","Taru Transport Black"], 
["Exile_Chopper_Taru_CSAT","Tari CSAT"], 
["Exile_Chopper_Taru_Black","Taru Black"], 
["Exile_Chopper_Taru_Covered_CSAT","Taru Covered CSAT"], 
["Exile_Chopper_Taru_Covered_Black","Taru Covered Black"], 
["O_Heli_Transport_04_F","Taru Transport"], 
["O_Heli_Transport_04_ammo_F","Taru Transport Ammo"], 
["O_Heli_Transport_04_bench_F","Taru Transport Bench"], 
["O_Heli_Transport_04_box_F","Taru Transport Box"], 
["O_Heli_Transport_04_covered_F","Taru Transport Covered"], 
["O_Heli_Transport_04_fuel_F","Taru Transport Fuel"], 
["O_Heli_Transport_04_medevac_F","Taru Transport Medivac"], 
["O_Heli_Transport_04_repair_F","Taru Transport Repair"], 
["O_Heli_Transport_04_black_F","Taru Transport Black"], 
["O_Heli_Transport_04_ammo_black_F","Taru Transport Ammo Black"], 
["O_Heli_Transport_04_bench_black_F","Taru Transport Bench Black"], 
["O_Heli_Transport_04_box_black_F","Taru Transport Box Black"], 
["O_Heli_Transport_04_covered_black_F","Taru Transport Covered Black"], 
["O_Heli_Transport_04_fuel_black_F","Taru Transport Fuel black"], 
["O_Heli_Transport_04_medevac_black_F","Taru Transport Medivac Black"], 
["O_Heli_Transport_04_repair_black_F","Taru Transport Repair Black"], 
["B_Heli_Attack_01_F","Blackfoot"], 
["B_Heli_Transport_01_F","Ghosthawk"], 
["B_Heli_Transport_01_camo_F","Ghosthawk Camo"], 
["B_CTRG_Heli_Transport_01_tropic_F","Ghosthawk Tropic"], 
["B_CTRG_Heli_Transport_01_sand_F","Ghosthawk Sand"], 
["B_Heli_Attack_01_dynamicLoadout_F","Comanche"], 
["O_Heli_Attack_02_F","Kajman "], 
["O_Heli_Attack_02_black_F","Kajman Black"], 
["B_T_VTOL_01_infantry_F","V-44 Blackfish Infantry"], 
["B_T_VTOL_01_infantry_blue_F","V-44 Blackfish Infantry Blue"], 
["B_T_VTOL_01_infantry_olive_F","V-44 Blackfish Infantry Olive"], 
["B_T_VTOL_01_vehicle_F","V-44 Blackfish Vehicle"], 
["B_T_VTOL_01_vehicle_blue_F","V-44 Blackfish Vehicle Blue"], 
["B_T_VTOL_01_vehicle_olive_F","V-44 Blackfish Vehicle Olive"], 
["B_T_VTOL_01_armed_F","Blackfish Armed"], 
["B_T_VTOL_01_armed_blue_F","Blackfish Armed Blue"], 
["B_T_VTOL_01_armed_olive_F","Blackfish Armed Olive"], 
["O_T_VTOL_02_infantry_F","Y-32 Xi'an Infantry"], 
["O_T_VTOL_02_vehicle_F","Y-32 Xi'an Vehicle"], 
["O_T_VTOL_02_infantry_hex_F","Y-32 Xi'an Infantry Hex"], 
["O_T_VTOL_02_infantry_ghex_F","Y-32 Xi'an Infantry Green Hex"], 
["O_T_VTOL_02_infantry_grey_F","Y-32 Xi'an Infantry Grey"], 
["O_T_VTOL_02_vehicle_hex_F","Y-32 Xi'an Vehicle Hex"], 
["O_T_VTOL_02_vehicle_ghex_F","Y-32 Xi'an Vehicle Green Hex"], 
["O_T_VTOL_02_vehicle_grey_F","Y-32 Xi'an Vehicle Grey"], 
["Exile_Plane_Cessna","Cessna"], 
["Exile_Plane_Ceasar","Ceasar"], 
["Exile_Plane_BlackfishInfantry","Blackfish Infantry"], 
["Exile_Plane_BlackfishVehicle","Blackfish Vehicle"], 
["Exile_Plane_AN2_Green","Antonov An-2 Green"], 
["Exile_Plane_AN2_White","Antonov An-2 White"], 
["Exile_Plane_AN2_Stripe","Antonov An-2 Stripe"], 
["GNT_C185","Cessna 185 Skywagon"], 
["GNT_C185F","Cessna 185 Skywagon"], 
["GNT_C185T","Cessna 185 Skywagon"], 
["C_Plane_Civil_01_F","Caesar BTT"], 
["C_Plane_Civil_01_racing_F","Caesar BTT Racing"], 
["I_C_Plane_Civil_01_F","Caesar BTT"], 
["B_Plane_CAS_01_F","A-164 Wipeout (CAS)"], 
["O_Plane_CAS_02_F","To-199 Neophron (CAS)"], 
["I_Plane_Fighter_03_CAS_F","A-143 Buzzard (CAS)"], 
["I_Plane_Fighter_03_AA_F","A-143 Buzzard (AA)"], 
["B_Plane_Fighter_01_F","F/A181 Black Wasp II"], 
["B_Plane_Fighter_01_Stealth_F","F/A-181 Black Wasp II(Stealth)"], 
["O_Plane_Fighter_02_F","To-201 Shikra"], 
["O_Plane_Fighter_02_Stealth_F","To-201 Shikra (Stealth)"], 
["I_Plane_Fighter_04_F","A-149 Gryphon"], 
["Exile_Boat_WaterScooter","Water Scooter"], 
["C_Scooter_Transport_01_F","Water Scooter"], 
["Exile_Boat_RubberDuck_CSAT","Rubberduck CSAT"], 
["Exile_Boat_RubberDuck_Digital","Rubberduck Digital"], 
["Exile_Boat_RubberDuck_Orange","Rubberduck Orange"], 
["Exile_Boat_RubberDuck_Blue","Rubberduck Blue"], 
["Exile_Boat_RubberDuck_Black","Rubberduck Black"], 
["C_Rubberboat","Rubberboat"], 
["B_Lifeboat","Lifeboat"], 
["O_Lifeboat","Lifeboat"], 
["B_T_Lifeboat","Lifeboat"], 
["O_T_Lifeboat","Lifeboat"], 
["B_Boat_Transport_01_F","Assault Boat"], 
["O_Boat_Transport_01_F","Assault Boat"], 
["B_G_Boat_Transport_01_F","Assault Boat"], 
["O_G_Boat_Transport_01_F","Assault Boat"], 
["I_Boat_Transport_01_F","Assault Boat"], 
["I_G_Boat_Transport_01_F","Assault Boat"], 
["B_G_Boat_Transport_02_F","RHIB"], 
["O_G_Boat_Transport_02_F","RHIB"], 
["I_G_Boat_Transport_02_F","RHIB"], 
["I_C_Boat_Transport_02_F","RHIB"], 
["C_Boat_Transport_02_F","RHIB"], 
["Exile_Boat_MotorBoat_Police","Police Motorboat"], 
["Exile_Boat_MotorBoat_Orange","Motorboat Orange"], 
["Exile_Boat_MotorBoat_White","Motorboat White"], 
["C_Boat_Civil_01_F","Motorboat"], 
["C_Boat_Civil_01_rescue_F","Motorboat Rescue"], 
["C_Boat_Civil_01_police_F","Motorboat Police"], 
["B_Boat_Armed_01_minigun_F","Speedboat Minigun"], 
["O_Boat_Armed_01_hmg_F","Speedboat HMG"], 
["I_Boat_Armed_01_minigun_F","Speedboat Minigun"], 
["Exile_Boat_SDV_CSAT","SDV CSAT"], 
["Exile_Boat_SDV_Digital","SDV Digital"], 
["Exile_Boat_SDV_Grey","SDV Grey"], 
["B_SDV_01_F","SDV"], 
["O_SDV_01_F","SDV"], 
["I_SDV_01_F","SDV"], 
["rhsusf_mrzr4_d","MRZR4 Desert"], 
["rhsusf_mrzr4_w","MRZR4 Woodland"], 
["rhsusf_mrzr4_d_mud","MRZR4 Desert"], 
["rhsusf_mrzr4_w_mud","MRZR4 Woodland"], 
["rhs_uaz_vmf","UAZ"], 
["rhs_uaz_vv","UAZ"], 
["rhs_uaz_vdv","UAZ"], 
["RHS_UAZ_MSV_01","UAZ"], 
["rhs_uaz_open_vmf","UAZ Open"], 
["rhs_uaz_open_vv","UAZ Open"], 
["rhs_uaz_open_vdv","UAZ Open"], 
["rhs_uaz_open_MSV_01","UAZ Open"], 
["rhsgref_cdf_reg_uaz_ags","UAZ"], 
["rhsgref_cdf_reg_uaz_dshkm","UAZ dshkm"], 
["rhsgref_cdf_reg_uaz_spg9","UAZ SPG9"], 
["rhs_gaz66_zu23_vmf","UAZ ZU23"], 
["rhsgref_nat_ural_zu23","URAL ZU23"], 
["RHS_Ural_Zu23_VV_01","URAL ZU23"], 
["rhs_gaz66_vmf","GAZ 66 Tactical Truck"], 
["rhs_gaz66_vv","GAZ 66 Tactical Truck"], 
["rhs_gaz66_vdv","GAZ 66 Tactical Truck"], 
["rhs_gaz66_msv","GAZ 66 Tactical Truck"], 
["rhsgref_ins_gaz66","GAZ 66 Tactical Truck"], 
["rhsgref_cdf_gaz66","GAZ 66 Tactical Truck"], 
["rhsgref_cdf_b_gaz66","GAZ 66 Tactical Truck"], 
["rhsgref_ins_g_gaz66","GAZ 66 Tactical Truck"], 
["rhs_gaz66_r142_vmf","GAZ R142"], 
["rhs_gaz66_r142_vdv","GAZ R142"], 
["rhs_gaz66_r142_msv","GAZ R142"], 
["rhs_gaz66_r142_vv","GAZ R142"], 
["rhsgref_ins_gaz66_r142","GAZ R143"], 
["rhsgref_cdf_b_gaz66_r142","GAZ R144"], 
["rhsgref_ins_g_gaz66_r142","GAZ R145"], 
["rhsgref_cdf_gaz66_r142","GAZ R146"], 
["rhs_gaz66_ap2_msv","GAZ66 AP2"], 
["rhs_gaz66_ap2_vdv","GAZ66 AP2"], 
["rhs_gaz66_ap2_vmf","GAZ66 AP2"], 
["rhs_gaz66_ap2_vv","GAZ66 AP2"], 
["rhsgref_ins_gaz66_ap2","GAZ66 AP2"], 
["rhsgref_cdf_b_gaz66_ap2","GAZ66 AP2"], 
["rhsgref_ins_g_gaz66_ap2","GAZ66 AP2"], 
["rhsgref_cdf_gaz66_ap2","GAZ66 AP2"], 
["rhs_gaz66_repair_vmf","GAZ Repair"], 
["rhs_gaz66_repair_vdv","GAZ Repair"], 
["rhs_gaz66_repair_vv","GAZ Repair"], 
["rhs_gaz66_repair_msv","GAZ Repair"], 
["rhsgref_ins_gaz66_repair","GAZ Repair"], 
["rhsgref_cdf_b_gaz66_repair","GAZ Repair"], 
["rhsgref_ins_g_gaz66_repair","GAZ Repair"], 
["rhsgref_cdf_gaz66_repair","GAZ Repair"], 
["rhs_gaz66_ammo_vmf","Gaz Ammo"], 
["rhs_gaz66_ammo_msv","Gaz Ammo"], 
["rhs_gaz66_ammo_vdv","Gaz Ammo"], 
["rhs_gaz66_ammo_vv","Gaz Ammo"], 
["rhsgref_ins_gaz66_ammo","Gaz Ammo"], 
["rhsgref_cdf_b_gaz66_ammo","Gaz Ammo"], 
["rhsgref_ins_g_gaz66_ammo","Gaz Ammo"], 
["rhsgref_cdf_gaz66_ammo","Gaz Ammo"], 
["rhs_gaz66_flat_vdv","GAZ Flatbed"], 
["rhs_gaz66_flat_vmf","GAZ Flatbed"], 
["rhs_gaz66_flat_vv","GAZ Flatbed"], 
["rhs_gaz66_flat_msv","GAZ Flatbed"], 
["rhsgref_ins_gaz66_flat","GAZ Flatbed"], 
["rhsgref_cdf_b_gaz66_flat","GAZ Flatbed"], 
["rhsgref_ins_g_gaz66_flat","GAZ Flatbed"], 
["rhsgref_cdf_gaz66_flat","GAZ Flatbed"], 
["rhs_gaz66o_vdv","GAZ 660"], 
["rhs_gaz66o_vmf","GAZ 660"], 
["rhs_gaz66o_vv","GAZ 660"], 
["rhs_gaz66o_msv","GAZ 660"], 
["rhsgref_ins_gaz66o","GAZ 660"], 
["rhsgref_cdf_b_gaz66o","GAZ 660"], 
["rhsgref_ins_g_gaz66o","GAZ 660"], 
["rhsgref_cdf_gaz66o","GAZ 660"], 
["rhs_gaz66o_flat_vdv","GAZ 660 Flatbed"], 
["rhs_gaz66o_flat_vmf","GAZ 660 Flatbed"], 
["rhs_gaz66o_flat_vv","GAZ 660 Flatbed"], 
["rhs_gaz66o_flat_msv","GAZ 660 Flatbed"], 
["rhsgref_ins_gaz66o_flat","GAZ 660 Flatbed"], 
["rhsgref_cdf_b_gaz66o_flat","GAZ 660 Flatbed"], 
["rhsgref_ins_g_gaz66o_flat","GAZ 660 Flatbed"], 
["rhsgref_cdf_gaz66o_flat","GAZ 660 Flatbed"], 
["RHS_Ural_Civ_01","Ural Civilian 01"], 
["RHS_Ural_Civ_03","Ural Civilian 02"], 
["RHS_Ural_Civ_02","Ural Civilian 03"], 
["rhsgref_ins_ural_work","Ural Work"], 
["rhsgref_ins_g_ural_work","Ural Work"], 
["rhsgref_nat_ural_work","Ural Work"], 
["rhsgref_nat_ural","Ural"], 
["rhsgref_cdf_ural","Ural"], 
["rhsgref_ins_g_ural","Ural"], 
["rhsgref_cdf_b_ural","Ural"], 
["rhsgref_ins_ural","Ural"], 
["rhsgref_un_ural","Ural"], 
["RHS_Ural_Open_Civ_01","Ural Open Civilian 01"], 
["RHS_Ural_Open_Civ_02","Ural Open Civilian 02"], 
["RHS_Ural_Open_Civ_03","Ural Open Civilian 03"], 
["rhsgref_ins_ural_work_open","Ural Open Work"], 
["rhsgref_ins_g_ural_work_open","Ural Open Work"], 
["rhsgref_nat_ural_work_open","Ural Open Work"], 
["RHS_Ural_Open_MSV_01","Ural Open 01"], 
["RHS_Ural_Open_VDV_01","Ural Open 01"], 
["RHS_Ural_Open_VMF_01","Ural Open 01"], 
["RHS_Ural_Open_VV_01","Ural Open 01"], 
["rhsgref_ins_ural_open","Ural Open"], 
["rhsgref_cdf_b_ural_open","Ural Open"], 
["rhsgref_ins_g_ural_open","Ural Open"], 
["rhsgref_cdf_ural_open","Ural Open"], 
["rhsgref_nat_ural_open","Ural Open"], 
["RHS_Ural_MSV_01","Ural 01"], 
["RHS_Ural_VDV_01","Ural 01"], 
["RHS_Ural_VMF_01","Ural 01"], 
["RHS_Ural_VV_01","Ural 01"], 
["RHS_Ural_Open_Flat_MSV_01","Ural Open Flatbed"], 
["RHS_Ural_Open_Flat_VDV_01","Ural Open Flatbed"], 
["RHS_Ural_Open_Flat_VMF_01","Ural Open Flatbed"], 
["RHS_Ural_Open_Flat_VV_01","Ural Open Flatbed"], 
["RHS_Ural_Fuel_MSV_01","Ural Fuel 01"], 
["RHS_Ural_Fuel_VDV_01","Ural Fuel 01"], 
["RHS_Ural_Fuel_VMF_01","Ural Fuel 01"], 
["RHS_Ural_Fuel_VV_01","Ural Fuel 01"], 
["rhsgref_cdf_b_ural_fuel","Ural Fuel "], 
["rhsgref_cdf_ural_fuel","Ural Fuel "], 
["RHS_Ural_Flat_MSV_01","Ural Flat 01"], 
["RHS_Ural_Flat_VDV_01","Ural Flat 01"], 
["RHS_Ural_Flat_VMF_01","Ural Flat 01"], 
["RHS_Ural_Flat_VV_01","Ural Flat 01"], 
["rhs_kraz255b1_bmkt_vv","Kraz 225b1"], 
["rhs_kraz255b1_bmkt_vmf","Kraz 225b1"], 
["rhs_kraz255b1_bmkt_vdv","Kraz 225b1"], 
["rhs_kraz255b1_bmkt_msv","Kraz 225b1"], 
["rhsgref_ins_kraz255b1_flatbed","Kraz 225b1 Flatbed"], 
["rhsgref_ins_g_kraz255b1_flatbed","Kraz 225b1 Flatbed"], 
["rhs_kraz255b1_flatbed_vv","Kraz 225b1 Flatbed"], 
["rhs_kraz255b1_flatbed_vmf","Kraz 225b1 Flatbed"], 
["rhs_kraz255b1_flatbed_vdv","Kraz 225b1 Flatbed"], 
["rhs_kraz255b1_flatbed_msv","Kraz 225b1 Flatbed"], 
["rhs_kraz255b1_pmp_vv","Kraz 225b1 PMP"], 
["rhs_kraz255b1_pmp_vmf","Kraz 225b1 PMP"], 
["rhs_kraz255b1_pmp_vdv","Kraz 225b1 PMP"], 
["rhs_kraz255b1_pmp_msv","Kraz 225b1 PMP"], 
["rhsgref_ins_kraz255b1_fuel","Kraz 225b1 Fuel"], 
["rhsgref_ins_g_kraz255b1_fuel","Kraz 225b1 Fuel"], 
["rhs_kraz255b1_fuel_vv","Kraz 225b1 Fuel"], 
["rhs_kraz255b1_fuel_vmf","Kraz 225b1 Fuel"], 
["rhs_kraz255b1_fuel_vdv","Kraz 225b1 Fuel"], 
["rhs_kraz255b1_fuel_msv","Kraz 225b1 Fuel"], 
["rhs_typhoon_vdv","Thyphoon"], 
["rhs_kamaz5350_msv","Kamaz 5350"], 
["rhs_kamaz5350_vdv","Kamaz 5350"], 
["rhs_kamaz5350_vmf","Kamaz 5350"], 
["rhs_kamaz5350_vv","Kamaz 5350"], 
["rhs_kamaz5350_flatbed_cover_msv","Kamaz 5350 Flatbed Cover"], 
["rhs_kamaz5350_flatbed_cover_vdv","Kamaz 5350 Flatbed Cover"], 
["rhs_kamaz5350_flatbed_cover_vmf","Kamaz 5350 Flatbed Cover"], 
["rhs_kamaz5350_flatbed_cover_vv","Kamaz 5350 Flatbed Cover"], 
["rhs_kamaz5350_open_msv","Kamaz 5350 Open"], 
["rhs_kamaz5350_open_vdv","Kamaz 5350 Open"], 
["rhs_kamaz5350_open_vmf","Kamaz 5350 Open"], 
["rhs_kamaz5350_open_vv","Kamaz 5350 Open"], 
["rhs_kamaz5350_flatbed_msv","Kamaz 5350 Flatbed "], 
["rhs_kamaz5350_flatbed_vdv","Kamaz 5350 Flatbed "], 
["rhs_kamaz5350_flatbed_vmf","Kamaz 5350 Flatbed "], 
["rhs_kamaz5350_flatbed_vv","Kamaz 5350 Flatbed "], 
["rhsusf_m1025_d","M1025 Desert"], 
["rhsusf_m1025_d_s","M1025 Desert Snorkle"], 
["rhsusf_m1025_w","M1025 Woodland"], 
["rhsusf_m1025_w_s","M1025 Woodland Snorkle"], 
["rhsusf_m1025_d_m2","M1025 Desert M2"], 
["rhsusf_m1025_d_s_m2","M1025 Desert M2 Snorkle"], 
["rhsusf_m1025_w_m2","M1025 Woodland M2"], 
["rhsusf_m1025_w_s_m2","M1025 Woodland M2 Snorkle"], 
["rhsusf_m1025_d_Mk19","M1025 Desert MK 19"], 
["rhsusf_m1025_d_s_Mk19","M1025 Desert MK 19 Snorkle"], 
["rhsusf_m1025_w_Mk19","M1025 Woodland MK 19"], 
["rhsusf_m1025_w_s_Mk19","M1025 Woodland MK 19 Snorkle"], 
["rhsusf_m998_d_2dr","M998 Desert 2door"], 
["rhsusf_m998_d_s_2dr","M998 Desert 2door Snorkle"], 
["rhsusf_m998_w_2dr","M998 Woodland 2door"], 
["rhsusf_m998_w_s_2dr","M998 Woodland 2door Snorkle"], 
["rhsusf_m998_d_4dr","M998 Desert 4door"], 
["rhsusf_m998_d_s_4dr","M998 Desert 4door Snorkle"], 
["rhsusf_m998_w_4dr","M998 Woodland 4door"], 
["rhsusf_m998_w_s_4dr","M998 Woodland 4door Snorkle"], 
["rhsusf_m998_d_2dr_halftop","M998 Desert 2door Halftop"], 
["rhsusf_m998_d_s_2dr_halftop","M998 Desert 2door Halftop Snorkle"], 
["rhsusf_m998_w_2dr_halftop","M998 Woodland 2door Halftop"], 
["rhsusf_m998_w_s_2dr_halftop","M998 Woodland 2door Halftop Snorkle"], 
["rhsusf_m998_d_4dr_halftop","M998 Desert 4 door Halftop"], 
["rhsusf_m998_d_s_4dr_halftop","M998 Desert 4door Halftop Snorkle"], 
["rhsusf_m998_w_4dr_halftop","M998 Woodland 4door Halftop Snorkle"], 
["rhsusf_m998_w_s_4dr_halftop","M998 Woodland 4door Halftop Snorkle"], 
["rhsusf_m998_d_2dr_fulltop","M998 Desert 2door Fulltop"], 
["rhsusf_m998_d_s_2dr_fulltop","M998 Desert 2door Fulltop Snorkle"], 
["rhsusf_m998_w_2dr_fulltop","M998 Woodland 2door Fulltop"], 
["rhsusf_m998_w_s_2dr_fulltop","M998 Woodland 2doorFulltop"], 
["rhsusf_m998_d_4dr_fulltop","M998 Desert 4 door Fulltop"], 
["rhsusf_m998_d_s_4dr_fulltop","M998 Desert 4door Fulltop"], 
["rhsusf_m998_w_4dr_fulltop","M998 Woodland 4door Fulltop"], 
["rhsusf_m998_w_s_4dr_fulltop","M998 Woodland 4door Fulltop"], 
["rhssaf_m1151_olive","M1151 Olive"], 
["rhssaf_army_o_m1151_olive","M1151 ARMY Olive"], 
["rhsusf_m1151_usarmy_wd","M1151 USArmy Woodland"], 
["rhsusf_m1151_usarmy_d","M1151 USArmy Desert"], 
["rhsusf_m1151_usmc_wd","M1151 USMC Woodland"], 
["rhsusf_m1151_usmc_d","M1151 USMC Desert"], 
["rhsusf_m1151_m2_v1_usarmy_wd","M1151 M2 V1 USArmy Woodland"], 
["rhsusf_m1151_m2_v1_usarmy_d","M1151 M2 V1 USArmy Desert"], 
["rhsusf_m1151_m2_v2_usarmy_wd","M1151 M2 V2 USArmy Woodland"], 
["rhsusf_m1151_m2_v2_usarmy_d","M1151 M2 V2 USArmy Desert"], 
["rhsusf_m1151_m2_v3_usmc_wd","M1151 M2 V3 USMC Woodland"], 
["rhsusf_m1151_m2_v3_usmc_d","M1151 M2 V3 USMC Desert"], 
["rhsusf_m1151_m2_lras3_v1_usarmy_wd","M1151 M2 IRAS3 V1 USArmy Woodland"], 
["rhsusf_m1151_m2_lras3_v1_usarmy_d","M1151 M2 IRAS3 V1 USArmy Desert"], 
["rhsusf_m1151_m240_v1_usarmy_wd","M1151 M240 V1 USArmy Woodland"], 
["rhsusf_m1151_m240_v1_usarmy_d","M1151 M240 V1 USArmy Desert"], 
["rhsusf_m1151_m240_v2_usarmy_wd","M1151 M240 V2 USArmy Woodland"], 
["rhsusf_m1151_m240_v2_usarmy_d","M1151 M240 V2 USArmy Desert"], 
["rhsusf_m1151_m240_v3_usmc_wd","M1151 M240 V3 USMC Woodland"], 
["rhsusf_m1151_m240_v3_usmc_d","M1151 M240 V3 USMC Desert"], 
["rhsusf_m1151_mk19_v1_usarmy_wd","M1151 MK19 V1 USArmy Woodland"], 
["rhsusf_m1151_mk19_v1_usarmy_d","M1151 MK19V1 USArmy Desert"], 
["rhsusf_m1151_mk19_v2_usarmy_wd","M1151 MK19 V2 USArmy Woodland"], 
["rhsusf_m1151_mk19_v2_usarmy_d","M1151 MK19 V2 USArmy Desert"], 
["rhsusf_m1151_mk19_v3_usmc_wd","M1151 MK19 V3 USMC Woodland"], 
["rhsusf_m1151_mk19_v3_usmc_d","M1151 MK19 V3 USMC Desert"], 
["rhsusf_m1151_m2crows_usarmy_wd","M1151 M2 CROWS USArmy Woodland"], 
["rhsusf_m1151_m2crows_usarmy_d","M1151 M2 CROWS USArmy Desert"], 
["rhsusf_m1151_m2crows_usmc_wd","M1151 M2 CROWS USMC Woodland"], 
["rhsusf_m1151_m2crows_usmc_d","M1151 M2 CROWS USMC Desert"], 
["rhsusf_m1151_mk19crows_usarmy_wd","M1151 M19 CROWS USArmy Woodland"], 
["rhsusf_m1151_mk19crows_usarmy_d","M1151 M19 CROWS USArmy Desert"], 
["rhsusf_m1151_mk19crows_usmc_wd","M1151 M19 CROWS USMC Woodland"], 
["rhsusf_m1151_mk19crows_usmc_d","M1151 M19 CROWS USMC Desert"], 
["rhssaf_army_o_m1151_olive_pkm","M1151 Army PKM Olive"], 
["rhssaf_m1151_olive_pkm","M1151 PKM Olive"], 
["rhssaf_m1152_olive","M1152 Olive"], 
["rhssaf_army_o_m1152_olive","M1152 Army Olive"], 
["rhsusf_m1152_usarmy_wd","M1152 US Army Woodland"], 
["rhsusf_m1152_usarmy_d","M1152 US Army Desert"], 
["rhsusf_m1152_usmc_wd","M1152 USMC Woodland"], 
["rhsusf_m1152_usmc_d","M1152 USMC Desert"], 
["rhssaf_m1152_TCV_olive","M1152 Olive"], 
["rhssaf_army_o_m1152_tcv_olive","M1152 Olive"], 
["rhsusf_m1152_rsv_usarmy_wd","M1152 Woodland"], 
["rhsusf_m1152_rsv_usarmy_d","M1152 Desert"], 
["rhssaf_army_o_m1152_rsv_olive","M1152 Olive"], 
["rhsusf_m1152_rsv_usmc_wd","M1152 USMC Woodland"], 
["rhsusf_m1152_rsv_usmc_d","M1152 USMC Desert"], 
["rhssaf_m1152_rsv_olive","M1152 Olive"], 
["rhsusf_m1152_sicps_usarmy_wd","M1152 USArmy SICPS Woodland"], 
["rhsusf_m1152_sicps_usarmy_d","M1152 USArmySICPS Desert"], 
["rhsusf_m1165_usarmy_wd","M1165 USArmy Woodland"], 
["rhsusf_m1165_usarmy_d","M1165 USArmy Desert"], 
["rhsusf_m1165_usmc_wd","M1165 USMC Woodland"], 
["rhsusf_m1165_usmc_d","M1165 USMC Desert"], 
["rhsusf_m1165_asv_m240_usaf_d","M1165 M240 USAF Desert ASV"], 
["rhsusf_m1165a1_gmv_m134d_m240_socom_d","M1165 M134D M240 SOCOM GMV Desert"], 
["rhsusf_m1165a1_gmv_m2_m240_socom_d","M1165 M2 M240 SOCOM GMV Desert"], 
["rhsusf_m1165a1_gmv_mk19_m240_socom_d","M1165 MK19 M240 SOCOM GMV Desert"], 
["rhs_tigr_vdv","GAZ Tiger"], 
["rhs_tigr_vmf","GAZ Tiger"], 
["rhs_tigr_msv","GAZ Tiger"], 
["rhs_tigr_vv","GAZ Tiger"], 
["rhs_tigr_3camo_vdv","Gaz Tiger Camo"], 
["rhs_tigr_3camo_vmf","Gaz Tiger Camo"], 
["rhs_tigr_3camo_msv","Gaz Tiger Camo"], 
["rhs_tigr_3camo_vv","Gaz Tiger Camo"], 
["rhs_tigr_ffv_vdv","GAZ Tiger Fire From Vehicle"], 
["rhs_tigr_ffv_vmf","GAZ Tiger Fire From Vehicle"], 
["rhs_tigr_ffv_msv","GAZ Tiger Fire From Vehicle"], 
["rhs_tigr_ffv_vv","GAZ Tiger Fire From Vehicle"], 
["rhs_tigr_ffv_3camo_vdv","GAZ Fire From Vehicle Camo"], 
["rhs_tigr_ffv_3camo_vmf","GAZ Fire From Vehicle Camo"], 
["rhs_tigr_ffv_3camo_msv","GAZ Fire From Vehicle Camo"], 
["rhs_tigr_ffv_3camo_vv","GAZ Fire From Vehicle Camo"], 
["rhs_tigr_sts_vdv","GAZ Tiger STS"], 
["rhs_tigr_sts_vmf","GAZ Tiger STS"], 
["rhs_tigr_sts_msv","GAZ Tiger STS"], 
["rhs_tigr_sts_vv","GAZ Tiger STS"], 
["rhs_tigr_sts_3camo_vdv","GAZ Tiger STS Camo"], 
["rhs_tigr_sts_3camo_vmf","GAZ Tiger STS Camo"], 
["rhs_tigr_sts_3camo_msv","GAZ Tiger STS Camo"], 
["rhs_tigr_sts_3camo_vv","GAZ Tiger STS Camo"], 
["rhs_tigr_m_vdv","GAZ Tiger M"], 
["rhs_tigr_m_vmf","GAZ Tiger M"], 
["rhs_tigr_m_msv","GAZ Tiger M"], 
["rhs_tigr_m_vv","GAZ Tiger M"], 
["rhs_tigr_m_3camo_vdv","GAZ Tiger M Camo"], 
["rhs_tigr_m_3camo_vmf","GAZ Tiger M Camo"], 
["rhs_tigr_m_3camo_msv","GAZ Tiger M Camo"], 
["rhs_tigr_m_3camo_vv","GAZ Tiger M Camo"], 
["rhsusf_m1240a1_usarmy_d","M1240 a1 USArmy Desert"], 
["rhsusf_m1240a1_usarmy_wd","M1240 a1 USArmy Woodland"], 
["rhsusf_m1240a1_usmc_d","M1240 a1 USMC Desert"], 
["rhsusf_m1240a1_usmc_wd","M1240 a1 USMC Woodland"], 
["rhsusf_m1240a1_m240_usarmy_d","M1240 a1 M 240 USArmy Desert"], 
["rhsusf_m1240a1_m240_usarmy_wd","M1240 a1 M 240 USArmy Woodland"], 
["rhsusf_m1240a1_m240_usmc_d","M1240 a1 M 240 USMC Desert"], 
["rhsusf_m1240a1_m240_usmc_wd","M1240 a1 M 240 USMC Woodland"], 
["rhsusf_m1240a1_m240_uik_usarmy_d","M1240 a1 M 240 USArmy Desert"], 
["rhsusf_m1240a1_m240_uik_usarmy_wd","M1240 a1 M 240 USArmy Woodland"], 
["rhsusf_m1240a1_m2_usarmy_d","M1240 a1 M2 USArmy Desert"], 
["rhsusf_m1240a1_m2_usarmy_wd","M1240 a1 M2 USArmy Woodland"], 
["rhsusf_m1240a1_m2_usmc_d","M1240 a1 M2 USMC Desert"], 
["rhsusf_m1240a1_m2_usmc_wd","M1240 a1 M2 USMC Woodland"], 
["rhsusf_m1240a1_m2_uik_usarmy_d","M1240 a1 M2 USMC Desert"], 
["rhsusf_m1240a1_m2_uik_usarmy_wd","M1240 a1 M2 USMC Woodland"], 
["rhsusf_m1240a1_m2crows_usarmy_d","M1240 a1 M2 CROWS USArmy Desert"], 
["rhsusf_m1240a1_m2crows_usarmy_wd","M1240 a1 M2 CROWS USArmy Woodland"], 
["rhsusf_m1240a1_m2crows_usmc_d","M1240 a1 M2 CROWS USMC Desert"], 
["rhsusf_m1240a1_m2crows_usmc_wd","M1240 a1 M2 CROWS USMC Woodland"], 
["rhsusf_m1240a1_mk19_usarmy_d","M1240 a1 MK19 USArmy Desert"], 
["rhsusf_m1240a1_mk19_usarmy_wd","M1240 a1 MK19 USArmy Woodland"], 
["rhsusf_m1240a1_mk19_usmc_d","M1240 a1 MK19 USMC Desert"], 
["rhsusf_m1240a1_mk19_usmc_wd","M1240 a1 MK19 USMC Woodland"], 
["rhsusf_m1240a1_mk19_uik_usarmy_d","M1240 a1 MK19 USArmy Desert"], 
["rhsusf_m1240a1_mk19_uik_usarmy_wd","M1240 a1 MK19 USArmy Woodland"], 
["rhsusf_m1240a1_mk19crows_usarmy_d","M1240 a1 MK19 CROWS USArmy Desert"], 
["rhsusf_m1240a1_mk19crows_usarmy_wd","M1240 a1 MK19 CROWS USArmy Woodland"], 
["rhsusf_m1240a1_mk19crows_usmc_d","M1240 a1 MK19 CROWS USMC Desert"], 
["rhsusf_m1240a1_mk19crows_usmc_wd","M1240 a1 MK19 CROWS USMC Woodland"], 
["rhsusf_m1245_m2crows_socom_d","M1240 a1 M2 CROWS USArmy SOCOM Desert"], 
["rhsusf_m1245_m2crows_socom_deploy","M1240 a1 M2 CROWS USArmy SOCOM Deploy"], 
["rhsusf_m1245_mk19crows_socom_d","M1240 a1 M2 CROWS USMC SOCOM Desert"], 
["rhsusf_m1245_mk19crows_socom_deploy","M1240 a1 M2 CROWS USMC SOCOM Deploy"], 
["rhsusf_M1117_D","M1117 Desert"], 
["rhsusf_M1117_O","M1117 Olive"], 
["rhsusf_M1117_W","M1117 Woodland"], 
["rhsgref_un_m1117","M1117 Unarmed"], 
["rhsusf_stryker_m1126_m2_d","M1126 Stryker M2 Desert"], 
["rhsusf_stryker_m1126_m2_wd","M1126 Stryker M2 Woodland"], 
["rhsusf_stryker_m1126_mk19_d","M1126 Stryker MK19 Desert"], 
["rhsusf_stryker_m1126_mk19_wd","M1126 Stryker MK19 Woodland"], 
["rhsusf_stryker_m1134_d","M1134 Stryker Desert"], 
["rhsusf_stryker_m1134_wd","M1134 Stryker Woodland"], 
["rhsusf_stryker_m1132_m2_np_wd","M1132 Stryker M2 Woodland"], 
["rhsusf_stryker_m1132_m2_np_d","M1132 Stryker M2 Desert"], 
["rhsusf_stryker_m1132_m2_d","M1132 Stryker M2 Desert"], 
["rhsusf_stryker_m1132_m2_wd","M1132 Stryker M2 Woodland"], 
["rhsusf_stryker_m1127_m2_d","M1127 Stryker M2 Desert"], 
["rhsusf_stryker_m1127_m2_wd","M1127 Stryker M2 Woodland"], 
["rhsusf_rg33_d","RG 33 Desert"], 
["rhsusf_rg33_wd","RG 33 Woodland"], 
["rhsusf_rg33_m2_d","RG 33 M2 Desert"], 
["rhsusf_rg33_m2_wd","RG 33 M2 Woodland"], 
["rhsusf_rg33_usmc_d","RG 33 USMC Desert"], 
["rhsusf_rg33_usmc_wd","RG 33 Usmc Woodland"], 
["rhsusf_rg33_m2_usmc_d","RG 33 M2 USMC Desert"], 
["rhsusf_rg33_m2_usmc_wd","RG 33 M2 USMC Woodland"], 
["rhsusf_M1220_usarmy_d","M1220 USArmy Desert"], 
["rhsusf_M1220_usarmy_wd","M1220 USArmy Woodland"], 
["rhsusf_M1220_M153_M2_usarmy_d","M1220 M153 M2 USArmy Desert"], 
["rhsusf_M1220_M153_M2_usarmy_wd","M1220 M153 M2 USArmy Woodland"], 
["rhsusf_M1220_M2_usarmy_d","M1220 M2 USArmy Desert"], 
["rhsusf_M1220_M2_usarmy_wd","M1220 M2 USArmy Woodland"], 
["rhsusf_M1220_MK19_usarmy_d","M1220 MK19 USArmy Desert"], 
["rhsusf_M1220_MK19_usarmy_wd","M1220 MK19 USArmy Woodland"], 
["rhsusf_M1220_M153_MK19_usarmy_d","M1220 M153 MK19 USArmy Desert"], 
["rhsusf_M1220_M153_MK19_usarmy_wd","M1220 M153 MK19 USArmy Woodland"], 
["rhsusf_M1230_M2_usarmy_wd","M1230 M2 USArmy Woodland"], 
["rhsusf_M1230_M2_usarmy_d","M1230 M2 USArmy Desert"], 
["rhsusf_M1230_MK19_usarmy_wd","M1230 MK19 USArmy Woodland"], 
["rhsusf_M1230_MK19_usarmy_d","M1230 MK19 USArmy Desert"], 
["rhsusf_M1230a1_usarmy_wd","M1230a1 USArmy Woodland"], 
["rhsusf_M1230a1_usarmy_d","M1230a1 USArmy Desert"], 
["rhsusf_M1232_usarmy_d","M1232 USArmy Desert"], 
["rhsusf_M1232_usarmy_wd","M1232 USArmy Woodland"], 
["rhsusf_M1232_M2_usarmy_d","M1232 M2 USArmy Desert"], 
["rhsusf_M1232_M2_usarmy_wd","M1232 M2 USArmy Woodland"], 
["rhsusf_M1232_MC_M2_usmc_d","M1232 *M2 USMC Desert"], 
["rhsusf_M1232_MC_M2_usmc_wd","M1232 *M2 USMC Woodland"], 
["rhsusf_M1232_MK19_usarmy_d","M1232 MK19 USArmy Desert"], 
["rhsusf_M1232_MK19_usarmy_wd","M1232 MK19 USArmy Woodland"], 
["rhsusf_M1232_MC_MK19_usmc_d","M1232 * MK19USMC Desert"], 
["rhsusf_M1232_MC_MK19_usmc_wd","M1232 * MK19USMC Woodland"], 
["rhsusf_M1237_M2_usarmy_d","M1237 M2 USArmy Desert"], 
["rhsusf_M1237_M2_usarmy_wd","M1237 M2 USArmy Woodland"], 
["rhsusf_M1237_MK19_usarmy_d","M1237 MK19 USArmy Desert"], 
["rhsusf_M1237_MK19_usarmy_wd","M1237 M19 USArmy Woodland"], 
["rhsusf_M1238A1_socom_d","M1238A1 SOCOM Desert"], 
["rhsusf_M1238A1_socom_wd","M1238A1 SOCOM Woodland"], 
["rhsusf_M1238A1_M2_socom_d","M1238A1 SOCOM M2 Desert"], 
["rhsusf_M1238A1_M2_socom_wd","M1238A1 SOCOM M2 Woodland"], 
["rhsusf_M1238A1_Mk19_socom_d","M1238A1 SOCOM MK19 Desert"], 
["rhsusf_M1238A1_Mk19_socom_wd","M1238A1 SOCOM MK19 Woodland"], 
["rhsusf_M1239_socom_d","M1239 SOCOM Desert"], 
["rhsusf_M1239_socom_wd","M1239 SOCOM Woodland"], 
["rhsusf_M1239_M2_socom_d","M1239 M2 SOCOM Desert"], 
["rhsusf_M1239_M2_socom_wd","M1239 M2 SOCOM Woodland"], 
["rhsusf_M1239_MK19_socom_d","M1239 MK19 SOCOM Desert"], 
["rhsusf_M1239_MK19_socom_wd","M1239 MK19 SOCOM Woodland"], 
["rhsusf_M1239_M2_Deploy_socom_d","M1239 M2 Deploy SOCOM Desert"], 
["rhsusf_M1239_M2_Deploy_socom_wd","M1239 M2 Deploy SOCOM Woodland"], 
["rhsusf_M1239_MK19_Deploy_socom_d","M1239 MK19 Deploy SOCOM Desert"], 
["rhsusf_M1239_MK19_Deploy_socom_wd","M1239 MK19 Deploy SOCOM Woodland"], 
["rhsusf_M977A4_usarmy_d","M977A4 USArmy Desert"], 
["rhsusf_M977A4_usarmy_wd","M977A4 USArmy Woodland"], 
["rhsusf_M977A4_BKIT_usarmy_d","M977A4 USArmy BKIT Desert"], 
["rhsusf_M977A4_BKIT_usarmy_wd","M977A4 USArmy BKIT Woodland "], 
["rhsusf_M977A4_BKIT_M2_usarmy_d","M977A4 USArmy M2 BKIT Desert"], 
["rhsusf_M977A4_BKIT_M2_usarmy_wd","M977A4 USArmy M3 BKIT Woodland"], 
["rhsusf_M977A4_AMMO_usarmy_d","M977A4 USArmy AMMO Desert"], 
["rhsusf_M977A4_AMMO_usarmy_wd","M977A4 USArmy AMMO Woodland"], 
["rhsusf_M977A4_AMMO_BKIT_usarmy_d","M977A4 USArmy AMMO BKIT Desert"], 
["rhsusf_M977A4_AMMO_BKIT_usarmy_wd","M977A4 USArmy AMMO BKIT Woodland"], 
["rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d","M977A4 USArmy M2 AMMO BKIT M2 Desert"], 
["rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd","M977A4 USArmy M2 AMMO BKIT Woodland"], 
["rhsusf_M977A4_REPAIR_usarmy_d","M977A4 USArmy REPAIR Desert"], 
["rhsusf_M977A4_REPAIR_usarmy_wd","M977A4 USArmy REPAIR Woodland"], 
["rhsusf_M977A4_REPAIR_BKIT_usarmy_d","M977A4 USArmy REPAIR BKIT Desert"], 
["rhsusf_M977A4_REPAIR_BKIT_usarmy_wd","M977A4 USArmy REPAIR BKIT Woodland"], 
["rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d","M977A4 USArmy M2 REPAIR BKIT M2 Desert"], 
["rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd","M977A4 USArmy M2 REPAIR BKIT Woodland"], 
["rhsusf_M978A4_usarmy_d","M978A4 USArmy Desert"], 
["rhsusf_M978A4_usarmy_wd","M978A4 USArmy Woodland"], 
["rhsusf_M978A4_BKIT_usarmy_d","M978A4 USArmy BKIT Desert"], 
["rhsusf_M978A4_BKIT_usarmy_wd","M978A4 USArmy BKIT Woodland"], 
["rhsusf_M1078A1P2_d_fmtv_usarmy","M1078AP2 USArmy Desert"], 
["rhsusf_M1078A1P2_wd_fmtv_usarmy","M1078AP2 USArmy Woodland "], 
["rhsusf_M1078A1P2_B_d_fmtv_usarmy","M1078AP2 B USArmy Desert"], 
["rhsusf_M1078A1P2_B_wd_fmtv_usarmy","M1078AP2 B USArmy Woodland "], 
["rhsusf_M1078A1P2_B_M2_d_fmtv_usarmy","M1078AP2 B M2 USArmy Desert"], 
["rhsusf_M1078A1P2_B_M2_wd_fmtv_usarmy","M1078AP2 B M2 USArmy Woodland"], 
["rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy","M1078A1P2 USArmy Flatbed Desert"], 
["rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy","M1078A1P2 USArmy Flatbed Woodland"], 
["rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy","M1078A1P2 B USArmy Flatbed Desert"], 
["rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy","M1078A1P2 B USArmy Flatbed Woodland"], 
["rhsusf_M1078A1P2_B_M2_d_flatbed_fmtv_usarmy","M1078A1P2 B M2 USArmy Flatbed Desert"], 
["rhsusf_M1078A1P2_B_M2_wd_flatbed_fmtv_usarmy","M1078A1P2 B M2 USArmy Flatbed Woodland"], 
["rhsusf_M1078A1P2_d_open_fmtv_usarmy","M1078A1P2 USArmy Open Desert"], 
["rhsusf_M1078A1P2_wd_open_fmtv_usarmy","M1078A1P2 USArmy Open Woodland"], 
["rhsusf_M1078A1P2_B_d_open_fmtv_usarmy","M1078A1P2 B USArmy Open Desert"], 
["rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy","M1078A1P2 B USArmy Open Woodland"], 
["rhsusf_M1078A1P2_B_M2_d_open_fmtv_usarmy","M1078A1P2 B M2 USArmy Open Desert"], 
["rhsusf_M1078A1P2_B_M2_wd_open_fmtv_usarmy","M1078A1P2 B M2 USArmy Open Woodland"], 
["rhsusf_M1078A1R_SOV_M2_D_fmtv_socom","M1078A1P2 SOV M2 SOCOM Desert"], 
["rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom","M1078A1P2 SOV M2 SOCOM Woodland"], 
["rhsusf_M1083A1P2_D_fmtv_usarmy","M1083A1P2 USArmy Desert"], 
["rhsusf_M1083A1P2_WD_fmtv_usarmy","M1083A1P2 USArmy Woodland "], 
["rhsusf_M1083A1P2_B_D_fmtv_usarmy","M1083A1P2 B USArmy Desert"], 
["rhsusf_M1083A1P2_B_WD_fmtv_usarmy","M1083A1P2 B USArmy Woodland "], 
["rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy","M1083A1P2 B M2 USArmy Desert"], 
["rhsusf_M1083A1P2_B_M2_WD_fmtv_usarmy","M1083A1P2 B M2 USArmy Woodland"], 
["rhsusf_M1083A1P2_D_open_fmtv_usarmy","M1083A1P2 USArmy Open Desert"], 
["rhsusf_M1083A1P2_WD_open_fmtv_usarmy","M1083A1P2 USArmy Open Woodland"], 
["rhsusf_M1083A1P2_B_D_open_fmtv_usarmy","M1083A1P2 B USArmy Open Desert"], 
["rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy","M1083A1P2 B USArmy Open Woodland"], 
["rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy","M1083A1P2 B M2 USArmy Open Desert"], 
["rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy","M1083A1P2 B M2 USArmy Open Woodland"], 
["rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy","M1083A1P2 USArmy Flatbed Desert"], 
["rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy","M1083A1P2 USArmy Flatbed Woodland"], 
["rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy","M1083A1P2 B USArmy Flatbed Desert"], 
["rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy","M1083A1P2 B USArmy Flatbed Woodland"], 
["rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy","M1083A1P2 B M2 USArmy Flatbed Desert"], 
["rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy","M1083A1P2 B M2 USArmy Flatbed Woodland"], 
["rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy","M1083A1P2 B USArmy Flatbed Desert"], 
["rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy","M1083A1P2 B USArmy Flatbed Woodland"], 
["rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy","M1083A1P2 B M2 USArmy Flatbed Desert"], 
["rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy","M1083A1P2 B M2 USArmy Flatbed Woodland"], 
["rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy","M1083A1P2 B M2 USArmy "], 
["rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy","M1083A1P2 B M2 USArmy Flatbed HQ Woodland"], 
["rhsusf_M1084A1P2_D_fmtv_usarmy","M1084A1P2 USArmy Open Desert"], 
["rhsusf_M1084A1P2_WD_fmtv_usarmy","M1084A1P2 USArmy Open Woodland"], 
["rhsusf_M1084A1P2_B_D_fmtv_usarmy","M1084A1P2 B USArmy Open Desert"], 
["rhsusf_M1084A1P2_B_WD_fmtv_usarmy","M1084A1P2 B USArmy Open Woodland"], 
["rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy","M1084A1P2 B M2 USArmy Open Desert"], 
["rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy","M1084A1P2 B M2 USArmy Open Woodland"], 
["rhsusf_M1084A1R_SOV_M2_D_fmtv_socom","M1084A1P2 SOV M2 SOCOM Desert"], 
["rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom","M1084A1P2 SOV M2 SOCOM Woodland"], 
["rhsgref_BRDM2","BRDM2"], 
["rhsgref_BRDM2_vmf","BRDM2"], 
["rhsgref_BRDM2_vdv","BRDM2"], 
["rhsgref_BRDM2_msv","BRDM2"], 
["rhsgref_BRDM2_ins","BRDM2"], 
["rhsgref_BRDM2_ins_g","BRDM2"], 
["rhsgref_BRDM2_b","BRDM2"], 
["rhsgref_BRDM2UM","BRDM 2UM"], 
["rhsgref_BRDM2_ATGM","BRDM 2UM ATGM"], 
["rhsgref_BRDM2UM_msv","BRDM 2UM"], 
["rhsgref_BRDM2UM_ins","BRDM 2UM"], 
["rhsgref_BRDM2UM_vdv","BRDM 2UM"], 
["rhsgref_BRDM2UM_vmf","BRDM 2UM"], 
["rhsgref_BRDM2UM_b","BRDM 2UM"], 
["rhsgref_BRDM2UM_ins_g","BRDM 2UM"], 
["rhsgref_BRDM2_HQ","BRDM2 Command"], 
["rhsgref_BRDM2_HQ_vmf","BRDM2 Command"], 
["rhsgref_BRDM2_HQ_vdv","BRDM2 Command"], 
["rhsgref_BRDM2_HQ_msv","BRDM2 Command"], 
["rhsgref_BRDM2_HQ_ins","BRDM2 Command"], 
["rhsgref_BRDM2_HQ_ins_g","BRDM2 Command"], 
["rhsgref_BRDM2_HQ_b","BRDM2 Command"], 
["rhs_btr60_vmf","BTR 60"], 
["rhs_btr60_vdv","BTR 60"], 
["rhs_btr60_vv","BTR 60"], 
["rhs_btr60_msv","BTR 60"], 
["RHS_BTR70","BTR70"], 
["RHS_BTR70_MSV","BTR70"], 
["RHS_BTR70_VDV","BTR70"], 
["RHS_BTR70_VMF","BTR70"], 
["RHS_BTR70_VV","BTR70"], 
["RHS_BTR80_MSV","BTR80"], 
["RHS_BTR80_VDV","BTR80"], 
["RHS_BTR80_VMF","BTR80"], 
["RHS_BTR80_VV","BTR80"], 
["RHS_BTR80A_MSV","BTR80 A"], 
["RHS_BTR80A_VDV","BTR80 A"], 
["RHS_BTR80A_VMF","BTR80 A"], 
["RHS_BTR80A_VV","BTR80 A"], 
["rhsgref_cdf_b_btr80","BTR80"], 
["rhsgref_cdf_btr80","BTR80"], 
["rhsusf_m113_usarmy_unarmed","M113 USArmy Unarmed"], 
["rhsusf_m113d_usarmy_unarmed","M113 USArmy Unarmed"], 
["rhsgref_hidf_m113a3_unarmed","M113a3 USArmy Unarmed"], 
["rhsusf_m113_usarmy_supply","M113 USArmy Supply"], 
["rhsusf_m113d_usarmy_supply","M113 USArmy Supply Desert"], 
["rhsusf_m113_usarmy_medical","M113 USArmy Medical"], 
["rhsusf_m113d_usarmy_medical","M113 USArmy Medical Desert"], 
["rhsusf_m113_usarmy","M113 USArmy Unarmed"], 
["rhsusf_m113d_usarmy","M113d USArmy Unarmed"], 
["rhsgref_hidf_m113a3_m2","M113a3 USArmy M2"], 
["rhsusf_m113_usarmy_M2_90","M113 USArmy M2"], 
["rhsusf_m113_usarmy_M240","M113 USArmy M240"], 
["rhsusf_m113d_usarmy_M240","M113d USArmy M240"], 
["rhsusf_m113_usarmy_MK19","M113 USArmy MK19"], 
["rhsusf_m113d_usarmy_MK19","M113d USArmy MK19"], 
["rhsgref_hidf_m113a3_mk19","M113a3 USArmy MK19"], 
["rhsusf_m113_usarmy_MK19_90","M113 USArmy MK19"], 
["RHS_M2A2","M2A2 Bradley"], 
["RHS_M2A2_wd","M2A2 Bradley Woodland"], 
["RHS_M2A2_BUSKI","M2A2 Bradley BUSKI"], 
["RHS_M2A2_BUSKI_WD","M2A2 Bradley BUSKI Woodland"], 
["RHS_M2A3","M2A3 IFV"], 
["RHS_M2A3_wd","M2A3 IFV Woodland"], 
["RHS_M2A3_BUSKI","M2A3 BUSKI"], 
["RHS_M2A3_BUSKI_wd","M2A3 BUSKI Woodland"], 
["RHS_M2A3_BUSKIII","M2A3 BUSKIII"], 
["RHS_M2A3_BUSKIII_wd","M2A3 BUSKIII Woodland"], 
["RHS_M6","M6 Bradley Desert"], 
["RHS_M6_wd","M6 Bradley Woodland"], 
["rhs_bmp1_msv","BMP1 "], 
["rhs_brm1k_msv","BRM1K"], 
["rhs_bmd1k","BMD1K"], 
["rhs_bmp3_msv","BMP3"], 
["rhs_bmp3_late_msv","BMP3"], 
["rhs_bmp3m_msv","BMP3m"], 
["rhs_bmp3mera_msv","BMP3mera"], 
["rhs_prp3_vv","PRP3"], 
["rhs_prp3_vmf","PRP3"], 
["rhs_prp3_vdv","PRP3"], 
["rhs_prp3_tv","PRP3"], 
["rhs_prp3_msv","PRP3"], 
["rhs_bmd4_vdv","BMD4"], 
["rhs_bmd4m_vdv","BMD4"], 
["rhs_bmd4ma_vdv","BMD4"], 
["rhssaf_army_pts","Tracked Amphibious Transport"], 
["rhs_pts_vmf","Tracked Amphibious Transport"], 
["rhsusf_m1a1fep_wd","M1A1 Abrams FEP Woodland"], 
["rhsusf_m1a1fep_od","M1A1 Abrams FEP Olive Drab"], 
["rhsusf_m1a1hc_wd","M1A1 Abrams HC FEP Woodland"], 
["rhsusf_m1a1fep_d","M1A1 Abrams FEP Desert"], 
["rhsusf_m1a1aimwd_usarmy","M1A1 AIM USArmy Woodland"], 
["rhsusf_m1a1aim_tuski_wd","M1A1 AIM TUSKI USArmy Woodland"], 
["rhsusf_m1a1aim_tuski_d","M1A1 AIM TUSKI USArmy Desert"], 
["rhsusf_m1a1aimd_usarmy","M1A1 AIM USArmy"], 
["rhsusf_m1a2sep1d_usarmy","M1A1 SEP1 USArmy Desert"], 
["rhsusf_m1a2sep1wd_usarmy","M1A2 Abrams SEP1 USArmy Woodland"], 
["rhsusf_m1a2sep1tuskid_usarmy","M1A2 Abrams SEP1 TUSKI USArmy Desert"], 
["rhsusf_m1a2sep1tuskiwd_usarmy","M1A2 Abrams SEP1 TUSKI USArmy Woodland"], 
["rhsusf_m1a2sep1tuskiid_usarmy","M1A2 Abrams SEP1 TUSKII USArmy Desert"], 
["rhsusf_m1a2sep1tuskiiwd_usarmy","M1A2 Abrams SEP1 TUSKII USArmy Woodland"], 
["rhsusf_m1a2sep2d_usarmy","M1A2 Abrams SEP2 USArmy Desert"], 
["rhsusf_m1a2sep2wd_usarmy","M1A2 Abrams SEP2 USArmy Woodland"], 
["rhs_t72ba_tv","T72 BA"], 
["rhs_t72bb_tv","T72 BB"], 
["rhs_t72bc_tv","T72 BC"], 
["rhs_t72bd_tv","T72 BD"], 
["rhs_t15_tv","T15"], 
["rhs_t80","T80"], 
["rhs_t80a","T80A"], 
["rhs_t80b","T80B"], 
["rhs_t80bk","T80BK"], 
["rhs_t80bv","T80 BV"], 
["rhs_t80bvk","T80 BVK"], 
["rhs_t80u","T80"], 
["rhs_t80u45m","T80"], 
["rhs_t80ue1","T80"], 
["rhs_t80uk","T80"], 
["rhs_t80um","T80"], 
["rhs_t90_tv","T90"], 
["rhs_t90a_tv","T90"], 
["rhsgref_ins_zsu234","ZSU 234"], 
["rhsgref_cdf_b_zsu234","ZSU 234"], 
["rhsgref_ins_g_zsu234","ZSU 234"], 
["rhsgref_cdf_zsu234","ZSU 234"], 
["rhs_2s3_tv","2S3M1 Akatsiya"], 
["rhs_ka60_c","KA 60 Killer Whale"], 
["rhs_ka60_grey","KA 60 Killer Whale Grey"], 
["RHS_UH60M_MEV","UH-60 Blackhawk Medivac"], 
["RHS_UH60M_MEV2","UH-60 Blackhawk Medivac2"], 
["RHS_UH60M","UH-60M Blackhawk"], 
["RHS_UH60M_d","UH-60M Blackhawk Desert"], 
["RHS_CH_47F","CH-47F Chinook"], 
["RHS_CH_47F_cargo","CH-47F Chinook Cargo"], 
["RHS_CH_47F_10","CH-47F Chinook 10"], 
["RHS_CH_47F_10_cargo","CH-47F Chinook 10 Cargo"], 
["RHS_CH_47F_light","CH-47F Chinook Light"], 
["RHS_MELB_MH6M","AH6 Littlebird MELB"], 
["RHS_MELB_H6M","AH6 Littlebird MELB H6M"], 
["RHS_MELB_AH6M_H","AH6M Littlebird MELB "], 
["RHS_MELB_AH6M_L","AH6M Littlebird MELB"], 
["RHS_MELB_AH6M_M","AH6M Littlebird MELB"], 
["rhs_uh1h_hidf","Huey"], 
["rhs_uh1h_hidf_gunship","Huey Gunship"], 
["rhs_uh1h_idap","Huey Idap"], 
["rhs_uh1h_un","Huey Unarmed"], 
["rhs_uh1h_hidf_unarmed","Huey Unarmed"], 
["RHS_UH1Y_UNARMED_d","UHY1 Venom Unarmed Desert"], 
["RHS_UH1Y_UNARMED","UHY1 Venom Unarmed "], 
["RHS_UH1Y_FFAR","UHY1 Venom FFAR"], 
["RHS_UH1Y_FFAR_d","UHY1 Venom FFAR Desert"], 
["RHS_UH1Y_GS","UHY1 Venom Ground Support"], 
["RHS_UH1Y_d_GS","UHY1 Venom Ground Support Desert"], 
["RHS_UH1Y_d","UHY1 Venom Desert"], 
["RHS_UH1Y","UHY1 Venom"], 
["rhsusf_CH53E_USMC","CH-53E Super Stallion USMC"], 
["rhsusf_CH53E_USMC_D","CH-53E Super Stallion USMC Desert"], 
["rhsusf_CH53e_USMC_cargo","CH-53E Super Stallion USMC Cargo"], 
["rhsusf_CH53e_USMC_D_cargo","CH-53E Super Stallion USMC Cargo Desert"], 
["rhsusf_CH53E_USMC_GAU21","CH-53E Super Stallion USMC GAU21"], 
["rhsusf_CH53E_USMC_GAU21_D","CH-53E Super Stallion USMC GAU21 Desert"], 
["RHS_Ka52_vvsc","KA-52 Allegator"], 
["RHS_Ka52_vvs","KA-52 Allegator"], 
["RHS_Ka52_UPK23_vvs","KA-52 Allegator UPK23"], 
["RHS_Ka52_UPK23_vvsc","KA-52 Allegator UPK23"], 
["RHS_AH1Z","Bell AH-1Z Viper"], 
["RHS_AH1Z_GS","Bell AH-1Z Viper Ground Support"], 
["RHS_AH1Z_CS","Bell AH-1Z Viper"], 
["RHS_AH64D_wd_GS","AH-64D Apache Longbow Ground Support"], 
["RHS_AH64D_GS","AH-64D Apache Longbow Ground Support"], 
["RHS_AH64D_CS","AH-64D Apache Longbow"], 
["RHS_AH64D_AA","AH-64D Apache Longbow Air Support"], 
["RHS_AH64D_noradar","AH-64D Apache Longbow No Radar"], 
["RHS_AH64D_noradar_GS","AH-64D Apache Longbow No Radar Ground Support"], 
["RHS_AH64D_noradar_CS","AH-64D Apache Longbow No Radar"], 
["RHS_AH64D_noradar_AA","AH-64D Apache Longbow No Radar Air Support"], 
["RHS_AH64DGrey","AH-64D Apache Longbow No Radar Grey"], 
["rhsgref_mi24g_CAS","Mi24g Close Air Support"], 
["rhsgref_mi24g_FAB","Mi24g"], 
["rhsgref_mi24g_UPK23","Mi24g UPK23"], 
["RHS_Mi24Vt_vvs","Mi24V"], 
["RHS_Mi24P_vdv","Mi24P"], 
["RHS_Mi24P_vvs","Mi24P"], 
["RHS_Mi24P_vvsc","Mi24P"], 
["RHS_Mi24P_AT_vdv","Mi24P AT"], 
["RHS_Mi24P_AT_vvs","Mi24P AT"], 
["RHS_Mi24P_AT_vvsc","Mi24P AT"], 
["RHS_Mi24P_CAS_vdv","Mi24P CAS"], 
["RHS_Mi24P_CAS_vvs","Mi24P CAS"], 
["RHS_Mi24P_CAS_vvsc","Mi24P CAS"], 
["RHS_Mi24V_vdv","Mi24V"], 
["RHS_Mi24V_vvs","Mi24V"], 
["RHS_Mi24V_vvsc","Mi24V"], 
["RHS_Mi24V_AT_vdv","Mi24V Anti Tank"], 
["RHS_Mi24V_AT_vvs","Mi24V Anti Tank"], 
["RHS_Mi24V_AT_vvsc","Mi24V FAB"], 
["RHS_Mi24V_FAB_vdv","Mi24V FAB"], 
["RHS_Mi24V_FAB_vvs","Mi24V FAB"], 
["RHS_Mi24V_FAB_vvsc","Mi24V FAB"], 
["RHS_Mi24V_UPK23_vdv","Mi24V UPK23"], 
["RHS_Mi24V_UPK23_vvs","Mi24V UPK24"], 
["RHS_Mi24V_UPK23_vvsc","Mi24V UPK25"], 
["rhsgref_un_Mi24V","Mi24V"], 
["rhsgref_un_Mi24V_UPK","Mi24V UPK"], 
["rhsgref_cdf_Mi24D","Mi24D"], 
["rhs_mi28n_vvs","Mi28n"], 
["rhs_mi28n_s13_vvs","Mi28n S13"], 
["rhsgref_cdf_Mi35","Mi35"], 
["rhsgref_cdf_Mi35_AT","Mi35 Anti Tank"], 
["rhsgref_cdf_Mi35_UPK","Mi35 UPK"], 
["RHS_Mi8mt_vvs","Mi8MT"], 
["RHS_Mi8mt_vvsc","Mi8MT"], 
["RHS_Mi8mt_vdv","Mi8MT"], 
["RHS_Mi8mt_vv","Mi8MT"], 
["RHS_Mi8MTV3_vdv","Mi8MTV3"], 
["RHS_Mi8MTV3_FAB_vdv","Mi8MTV3 FAB"], 
["RHS_Mi8MTV3_UPK23_vdv","Mi8MTV3 UPK23"], 
["RHS_Mi8mtv3_Cargo_vdv","Mi8MTV3 Cargo"], 
["RHS_MI8MTV3_vvs","Mi8MTV3"], 
["RHS_Mi8MTV3_FAB_vvs","Mi8MTV3 FAB"], 
["RHS_MI8MTV3_UPK23_vvs","Mi8MTV3 UPK23"], 
["RHS_Mi8mtv3_Cargo_vvs","Mi8MTV3 Cargo"], 
["RHS_MI8MTV3_vvsc","Mi8MTV3"], 
["RHS_Mi8MTV3_FAB_vvsc","Mi8MTV3 FAB"], 
["RHS_MI8MTV3_UPK23_vvsc","Mi8MTV3 UPK23"], 
["RHS_Mi8mtv3_Cargo_vvsc","Mi8MTV3 Cargo"], 
["RHS_Mi8AMTSh_vvs","Mi8AMTSH"], 
["RHS_Mi8AMTSh_FAB_vvs","Mi8AMTSH FAB"], 
["RHS_Mi8AMTSh_UPK23_vvs","Mi8AMTSH UPK23"], 
["RHS_Mi8AMTSh_vvsc","Mi8AMTSH"], 
["RHS_Mi8AMTSh_FAB_vvsc","Mi8AMTSH FAB"], 
["RHS_Mi8AMTSh_UPK23_vvsc","Mi8AMTSH UPK23"], 
["rhsgref_cdf_reg_Mi17Sh","Mi17SH"], 
["rhsgref_cdf_reg_Mi17Sh_FAB","Mi17SH FAB"], 
["rhsgref_cdf_reg_Mi17Sh_UPK","Mi17SH UPK"], 
["RHS_Mi8AMT_vvs","Mi8AMT"], 
["RHS_Mi8AMT_vvsc","Mi8AMT"], 
["RHS_Mi8AMT_vdv","Mi8AMT"], 
["RHS_Mi8mt_Cargo_vvs","Mi8MT Cargo"], 
["RHS_Mi8mt_Cargo_vvsc","Mi8MT Cargo"], 
["RHS_Mi8mt_Cargo_vdv","Mi8MT Cargo"], 
["RHS_Mi8mt_Cargo_vv","Mi8MT Cargo"], 
["RHS_Mi8amt_civilian","Mi8AMT Civilian"], 
["rhsgref_ins_Mi8amt","Mi8AMT"], 
["rhsgref_cdf_reg_Mi8amt","Mi8AMT"], 
["rhsgref_un_Mi8amt","Mi8AMT Unarmed"], 
["rhsgred_hidf_cessna_o3a","Cessna Gray"], 
["RHS_AN2","Antonov An-2"], 
["RHS_AN2_B","Antonov An-2"], 
["RHS_C130J","C130J Super Hercules"], 
["RHS_C130J_Cargo","C130J Super Hercules Cargo"], 
["rhs_l159_CDF_CAP","L159 ALCA "], 
["rhs_l159_CDF_CAS","L159 ALCA Close Air Support"], 
["rhs_l159_CDF_plamen","L159 ALCA M-63 Plamen"], 
["rhs_l159_CDF","L159 ALCA "], 
["rhs_l159_cdf_b_CDF","L159 ALCA "], 
["rhs_l159_cdf_b_CDF_plamen","L159 ALCA M-63 Plamen"], 
["rhs_l159_cdf_b_CDF_CAP","L159 ALCA "], 
["rhs_l159_cdf_b_CDF_CAS","L159 ALCA Close Air Support"], 
["RHSGREF_A29B_HIDF","A29B Tunnan"], 
["rhs_l39_cdf","L39 Albatros"], 
["rhs_l39_cdf_b_cdf","L39 Albatros"], 
["RHS_A10","A-10 Warthog"], 
["RHS_A10_AT","A-10 Warthog Anti Tank"], 
["rhsusf_f22","F-22 Raptor"], 
["RHS_T50_vvs_generic","KAI T-50 Golden Eagle"], 
["RHS_T50_vvs_051","KAI T-50 Golden Eagle 051"], 
["RHS_T50_vvs_052","KAI T-50 Golden Eagle 052"], 
["RHS_T50_vvs_blueonblue","KAI T-50 Golden Eagle Blue on Blue"], 
["RHS_Su25SM_vvs","SU 25SM"], 
["RHS_Su25SM_CAS_vvs","SU 25SM Close Air Support"], 
["RHS_Su25SM_KH29_vvs","SU 25SM KH-29"], 
["RHS_Su25SM_vvsc","SU 25SM"], 
["RHS_Su25SM_CAS_vvsc","SU 25SM Close Air Support"], 
["RHS_Su25SM_KH29_vvsc","SU 25SM KH-29"], 
["rhsgref_cdf_su25","SU 25"], 
["RHS_TU95MS_vvs_irkutsk","Tupolev Tu-95 Bear"], 
["RHS_TU95MS_vvs_old","Tupolev Tu-95 Bear"], 
["RHS_TU95MS_vvs_dubna","Tupolev Tu-95 Bear"], 
["RHS_TU95MS_vvs_tambov","Tupolev Tu-95 Bear"], 
["RHS_TU95MS_vvs_chelyabinsk","Tupolev Tu-95 Bear"], 
["rhsusf_mkvsoc","MKV SOC"], 
["B_mas_cars_Hilux_Unarmed","Hilux Unarmed"], 
["B_mas_cars_Hilux_Med","Hilux Medical"], 
["I_mas_cars_UAZ_Unarmed","UAZ Unarmed"], 
["I_mas_cars_UAZ_Med","UAZ Medical"], 
["O_mas_cars_UAZ_Unarmed","UAZ Unarmed"], 
["O_mas_cars_UAZ_Med","UAZ Medical"], 
["B_mas_cars_LR_Unarmed","Landrover Unarmed"], 
["B_mas_cars_LR_Med","Landrover Medical"], 
["I_mas_cars_LR_soft_Unarmed","Landrover Unarmed"], 
["I_mas_cars_LR_soft_Med","Landrover Medical"], 
["B_mas_cars_Hilux_M2","Hilux M2"], 
["B_mas_cars_Hilux_MG","Hilux Machine Gun"], 
["B_mas_cars_Hilux_AGS30","Hilux AGS30"], 
["B_mas_cars_Hilux_SPG9","Hilux SPG9"], 
["B_mas_cars_Hilux_RKTS","Hilux RKTS"], 
["I_mas_cars_UAZ_M2","UAZ M2"], 
["I_mas_cars_UAZ_AGS30","UAZ AGS30"], 
["O_mas_cars_UAZ_AGS30","UAZ AGS30"], 
["I_mas_cars_UAZ_MG","UAZ Machine Gun"], 
["O_mas_cars_UAZ_MG","UAZ Machine Gun"], 
["O_mas_cars_UAZ_SPG9","UAZ SPG9"], 
["I_mas_cars_UAZ_SPG9","UAZ SPG9"], 
["B_mas_cars_LR_M2","Landrover M2"], 
["I_mas_cars_LR_soft_M2","Landrover M2"], 
["B_mas_cars_LR_Mk19","Landrover Mk19"], 
["I_mas_cars_LR_soft_Mk19","Landrover Mk19"], 
["B_mas_cars_LR_Stinger","Landrover Stinger"], 
["I_mas_cars_LR_soft_Stinger","Landrover Stinger"], 
["B_mas_cars_LR_TOW","Landrover TOW"], 
["I_mas_cars_LR_soft_TOW","Landrover TOW"], 
["B_mas_cars_LR_SPG9","Landrover SPG9"], 
["I_mas_cars_LR_soft_SPG9","Landrover SPG9"], 
["B_mas_HMMWV_UNA","Humvee Unarmed"], 
["B_mas_HMMWV_UNA_des","Humvee Unarmed Desert"], 
["B_mas_HMMWV_MEV","Humvee Medivac"], 
["B_mas_HMMWV_MEV_des","Humvee Medivac Desert"], 
["B_mas_HMMWV_M2_des","Humvee M2 Desert"], 
["B_mas_HMMWV_M2","Humvee M2"], 
["B_mas_HMMWV_M134_des","Humvee M134 Desert"], 
["B_mas_HMMWV_M134","Humvee M134"], 
["B_mas_HMMWV_MK19_des","Humvee Mk19 Desert"], 
["B_mas_HMMWV_MK19","Humvee Mk19 Desert"], 
["B_mas_HMMWV_SOV","Humvee SOV"], 
["B_mas_HMMWV_SOV_des","Humvee SOV Desert"], 
["B_mas_HMMWV_SOV_M134_des","Humvee SOV M134 Desert"], 
["B_mas_HMMWV_SOV_M134","Humvee SOV M134"], 
["B_mas_HMMWV_Stinger_des","Humvee Stinger Desert"], 
["B_mas_HMMWV_Stinger","Humvee Stinger"], 
["B_mas_HMMWV_TOW_des","Humvee TOW Desert"], 
["B_mas_HMMWV_TOW","Humvee TOW"], 
["I_mas_cars_Ural","Ural"], 
["O_mas_cars_Ural","Ural"], 
["I_mas_cars_Ural_open","Ural Open"], 
["O_mas_cars_Ural_open","Ural Open"], 
["I_mas_cars_Ural_repair","Ural Repair"], 
["O_mas_cars_Ural_repair","Ural Repair"], 
["I_mas_cars_Ural_fuel","Ural Fuel"], 
["O_mas_cars_Ural_fuel","Ural Fuel"], 
["I_mas_cars_Ural_ammo","Ural Ammo"], 
["O_mas_cars_Ural_ammo","Ural Ammo"], 
["RHS_BM21_MSV_01","Ural BM21"], 
["O_mas_cars_Ural_BM21","Ural BM21"], 
["I_mas_cars_Ural_ZU23","Ural ZU23"], 
["O_mas_cars_Ural_ZU23","Ural ZU23"], 
["I_mas_BRDM2","BRDM 2"], 
["O_mas_BRDM2","BRDM 2"], 
["I_mas_BTR60","BTR60"], 
["O_mas_BTR60","BTR60"], 
["I_mas_BMP2_Ambul_01","BMP2 Ambulance"], 
["O_mas_BMP2_Ambul_01","BMP2 Ambulance"], 
["I_mas_BMP1_AAF_01","BMP1"], 
["O_mas_BMP1_OPF_01","BMP1"], 
["I_mas_BMP1P_AAF_01","BMP1"], 
["O_mas_BMP1P_OPF_01","BMP1"], 
["rhs_bmp2_msv","BMP2"], 
["O_mas_BMP2_OPF_01","BMP2"], 
["I_mas_BMP2_HQ_AAF_01","BMP2"], 
["O_mas_BMP2_HQ_OPF_01","BMP2"], 
["I_mas_T72_AAF_01","T72"], 
["O_mas_T72_OPF_01","T72"], 
["I_mas_T72B_Early_AAF_01","T72"], 
["O_mas_T72B_Early_OPF_01","T72"], 
["I_mas_T72B_AAF_01","T72"], 
["O_mas_T72B_OPF_01","T72"], 
["I_mas_T72BM_AAF_01","T72"], 
["O_mas_T72BM_OPF_01","T72"], 
["I_mas_T55_AAF_01","T55"], 
["O_mas_T55_OPF_01","T55"], 
["I_mas_T34_AAF_01","T34"], 
["I_mas_ZSU_AAF_01","ZSU"], 
["O_mas_ZSU_OPF_01","ZSU"], 
["O_mas_T90_OPF_01","T90"], 
["B_mas_UH1Y_UNA_F","Venom Unarmed"], 
["B_mas_UH1Y_MEV_F","Venom Medivac"], 
["B_mas_UH60M_MEV","UH60M Meduvac"], 
["B_mas_UH1Y_F","Venom"], 
["B_mas_UH60M","UH 60M Blackhawk"], 
["B_mas_UH60M_SF","UH 60M Blackhawk"], 
["I_mas_MI8MTV","Mi8 MTV"], 
["O_mas_MI8MTV","Mi8 MTV"], 
["I_mas_MI8","Mi8 "], 
["O_mas_MI8","Mi8"], 
["I_mas_MI24V","Mi24V"], 
["O_mas_MI24V","Mi24V"], 
["B_mas_CH_47F","CH-47F Chinook"], 
["mas_F_35C","F35C"], 
["mas_F_35C_cas","F35C"], 
["mas_F_35C_cap","F35C"], 
["mas_F_35C_S","F35C"], 
["B_Plane_Fighter_01_Cluster_F","F/A 181 Black Wasp"], 
["RHS_AH64D","AH-64D Apache Longbow"], 
["B_T_MBT_01_cannon_F","M2A1 Slammer, Green"], 
["I_mas_cars_Ural_BM21","Ural BM21"], 
["RHS_AH64D_wd_AA","AH-64D Apache Longbow AA"], 
["RHS_UH60M_ESSS","UH-60M Blackhawk"], 
["Exile_Boat_RHIB","RHIB"], 
["rhs_t90sab_tv","T90"], 
["B_T_MRAP_01_hmg_F","Hunter HMG"], 
["B_T_MRAP_01_gmg_F","Hunter GMG"], 
["rhs_zsu234_aa","ZSU 234"], 
["LR_Ambulance_01","Landrover Ambulance Green"], 
["RHS_Civ_Truck_02_covered_F","Zamak Transport Civ"], 
["C_Truck_02_covered_F","Zamak Transport Civ"], 
["rhsusf_m1043_d_s_m2","M1043 Desert M2 Snorkle"], 
["rhsusf_m1043_d","M1043 Desert"], 
["rhsusf_m1043_w","M1043 Woodland"], 
["rhsusf_m1043_d_s","M1043 Desert, Snorkle"], 
["rhsusf_m1043_w_s","M1043 Woodland, Snorkle"], 
["rhsusf_m1043_d_m2","M1043 Desert, M2"], 
["rhsusf_m1043_w_m2","M1043 Woodland, M2"], 
["rhsusf_m1043_d_s_m2","M1043 Desert, M2, Snorkle"], 
["rhsusf_m1043_w_s_m2","M1043 Woodland, M2, Snorkle"], 
["rhsusf_m1043_d_mk19","M1043 Desert, MK19"], 
["rhsusf_m1043_w_mk19","M1043 Woodland, MK19"], 
["rhsusf_m1043_d_s_mk19","M1043 Desert, MK19, Snorkle"], 
["rhsusf_m1043_w_s_mk19","M1043 Woodland, MK19, Snorkle"], 
["O_Heli_Attack_02_dynamicLoadout_F","Kajman Black"], 
["I_mas_BMP2_AAF_01","BMP2"],
["B_MIRAGE_F1_F","Mirage F1"],
["O_MIRAGE_F1_F","Mirage F1"],
["I_MIRAGE_F1_F","Mirage F1"],
["RHICC_GREY","RHICC Assault Craft"],
["RHICC_GREEN","RHICC Assault Craft"],
["rhsgref_hidf_canoe","Poseidon II Kayak"],
["rhsgref_civ_canoe","Poseidon II Kayak"]
];
publicVariable "VehicleNameMap";

true
