R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
/*
//From A3_Vanilla
	"I_supplyCrate_F",
	"O_supplyCrate_F",
	"C_supplyCrate_F",
	"B_supplyCrate_F",
	"C_T_supplyCrate_F",
	"IG_supplyCrate_F",
	"C_IDAP_supplyCrate_F",
	"B_CargoNet_01_ammo_F",
	"I_CargoNet_01_ammo_F",
	"O_CargoNet_01_ammo_F",
	"Exile_Construction_SupplyBox_Preview",
	"C_IDAP_CargoNet_01_supplies_F",
	"CargoNet_01_barrels_F",
	"CargoNet_01_box_F",
	"Land_FoodSacks_01_cargo_white_idap_F",
	"Land_FoodSacks_01_cargo_brown_idap_F",
	"Land_FoodSacks_01_cargo_brown_F",
	"Box_IND_AmmoVeh_F",
	"Box_East_AmmoVeh_F",
	"Box_NATO_AmmoVeh_F",
	"Box_AAF_Uniforms_F",
	"Box_CSAT_Uniforms_F",
	"Box_NATO_Uniforms_F",
	"Box_IDAP_Uniforms_F",
	"Land_Ammobox_rounds_F",
	"Box_GEN_Equip_F",
	"Box_AAF_Equip_F",
	"Box_CSAT_Equip_F",
	"Box_NATO_Equip_F",
	"Box_IDAP_Equip_F",
	"Land_MetalCase_01_large_F",
	"Box_IND_Support_F",
	"Box_East_Support_F",
	"Box_NATO_Support_F",
	"Box_IND_Grenades_F",
	"Box_East_Grenades_F",
	"Box_NATO_Grenades_F",
	"Box_IND_AmmoOrd_F",
	"Box_East_AmmoOrd_F",
	"Box_NATO_AmmoOrd_F",
	"Box_IDAP_AmmoOrd_F",
	"Box_IED_Exp_F",
	"Box_IND_Ammo_F",
	"Box_East_Ammo_F",
	"Box_NATO_Ammo_F",
	"Box_T_East_Ammo_F",
	"Box_Syndicate_Ammo_F",
	"Box_IND_Wps_F",
	"Box_East_Wps_F",
	"Box_NATO_Wps_F",
	"Box_T_East_Wps_F",
	"Box_Exile_Weapons_1v",
	"Box_T_NATO_Wps_F",
*/	
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
/*
//From A3_Vanilla
	["B_supplycrate_f", 9],
	["C_supplycrate_f", 9],
	["Box_east_ammoveh_f", 14],
	["IG_supplycrate_f", 9],
	["Box_ind_ammoveh_f", 14],
	["Box_NATO_ammoveh_f", 14]
*/	
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
/*
//From A3_Vanilla
	"I_supplyCrate_F",
	"O_supplyCrate_F",
	"C_supplyCrate_F",
	"B_supplyCrate_F",
	"C_T_supplyCrate_F",
	"IG_supplyCrate_F",
	"C_IDAP_supplyCrate_F",
	"B_CargoNet_01_ammo_F",
	"I_CargoNet_01_ammo_F",
	"O_CargoNet_01_ammo_F",
	"Exile_Construction_SupplyBox_Preview",
	"C_IDAP_CargoNet_01_supplies_F",
	"CargoNet_01_barrels_F",
	"CargoNet_01_box_F",
	"Land_FoodSacks_01_cargo_white_idap_F",
	"Land_FoodSacks_01_cargo_brown_idap_F",
	"Land_FoodSacks_01_cargo_brown_F",
	"Box_IND_AmmoVeh_F",
	"Box_East_AmmoVeh_F",
	"Box_NATO_AmmoVeh_F",
	"Box_AAF_Uniforms_F",
	"Box_CSAT_Uniforms_F",
	"Box_NATO_Uniforms_F",
	"Box_IDAP_Uniforms_F",
	"Land_Ammobox_rounds_F",
	"Box_GEN_Equip_F",
	"Box_AAF_Equip_F",
	"Box_CSAT_Equip_F",
	"Box_NATO_Equip_F",
	"Box_IDAP_Equip_F",
	"Land_MetalCase_01_large_F",
	"Box_IND_Support_F",
	"Box_East_Support_F",
	"Box_NATO_Support_F",
	"Box_IND_Grenades_F",
	"Box_East_Grenades_F",
	"Box_NATO_Grenades_F",
	"Box_IND_AmmoOrd_F",
	"Box_East_AmmoOrd_F",
	"Box_NATO_AmmoOrd_F",
	"Box_IDAP_AmmoOrd_F",
	"Box_IED_Exp_F",
	"Box_IND_Ammo_F",
	"Box_East_Ammo_F",
	"Box_NATO_Ammo_F",
	"Box_T_East_Ammo_F",
	"Box_Syndicate_Ammo_F",
	"Box_IND_Wps_F",
	"Box_East_Wps_F",
	"Box_NATO_Wps_F",
	"Box_T_East_Wps_F",
	"Box_Exile_Weapons_1v",
	"Box_T_NATO_Wps_F",
	
//From "All in Arma"
	["guerillacacheBox", 5],
	["specialweaponsBox", 10],
	["rubasicammunitionBox", 5],
	["rubasicweaponsBox", 15],
	["ruspecialweaponsBox", 12],
	["ruvehicleBox", 50],
	["ammoBox_pmc", 5],
	["baf_vehicleBox", 30],
	["czbasicweapons_ep1", 5],
	["gerbasicweapons_ep1", 5],
	["guerillacacheBox_ep1", 5],
	["tkbasicammunitionBox_ep1", 5],
	["tkvehicleBox_ep1", 40],
	["tkbasicweapons_ep1", 5],
	["tklaunchers_ep1", 5],
	["tkspecialweapons_ep1", 5],
	["unbasicammunitionBox_ep1", 5],
	["unbasicweapons_ep1", 5],
	["usbasicammunitionBox_ep1", 5],
	["usvehicleBox_ep1", 30],
	["usbasicweapons_ep1", 5],
	["uslaunchers_ep1", 5],
	["usspecialweapons_ep1", 8],
	["usbasicammunitionBox", 5],
	["usvehicleBox", 20]
*/
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
//From A3_Vanilla
//	"reammoBox_f",
	"Exile_Container_SupplyBox",
	"C_IDAP_supplyCrate_F",

	"BSF_SupplyBox_Orange",
	"BSF_SupplyBox_Green",
	"BSF_ArmorLocker",
	"BSF_ArmorLocker_Optics",
	"BSF_ArmorLocker_Storage",
	"BSF_ArmorLocker_Tools",
	"BSF_ArmorLocker_Attachments",
	"BSF_ArmorLocker_Rifles",
	"BSF_ArmorLocker_Food",
	"BSF_ArmorLocker_Pistols",
	"BSF_ArmorLocker_Armor",
	"BSF_ArmorLocker_Ammo",	
	"BSF_ArmorLocker_ComChest",
	"BSF_ArmorLocker_Explosives",
	"BSF_ArmorLocker_HMG",
	"BSF_ArmorLocker_Junk",
	"BSF_ArmorLocker_Launchers",
	"BSF_ArmorLocker_LMG",
	"BSF_ArmorLocker_Materials",
	"BSF_ArmorLocker_Medical",
	"BSF_ArmorLocker_Packs",
	"BSF_ArmorLocker_Rifles_127",
	"BSF_ArmorLocker_Rifles_338",
	"BSF_ArmorLocker_Rifles_545",
	"BSF_ArmorLocker_Rifles_556",
	"BSF_ArmorLocker_Rifles_65",
	"BSF_ArmorLocker_Rifles_762",
	"BSF_ArmorLocker_Rifles_Misc",
	"BSF_ArmorLocker_Rifles_Sniper",
	"BSF_ArmorLocker_Shotguns",
	"BSF_ArmorLocker_SMG",
	"BSF_ArmorLocker_ToSell",
	"BSF_ArmorLocker_ToSort",
	"BSF_ArmorLocker_UAV",
	"BSF_ArmorLocker_Uniforms",

	"I_supplyCrate_F",
	"O_supplyCrate_F",
	"C_supplyCrate_F",
	"B_supplyCrate_F",
	"C_T_supplyCrate_F",
	"IG_supplyCrate_F",
	"B_CargoNet_01_ammo_F",
	"I_CargoNet_01_ammo_F",
	"O_CargoNet_01_ammo_F",
	"Exile_Construction_SupplyBox_Preview",
	"C_IDAP_CargoNet_01_supplies_F",
	"CargoNet_01_barrels_F",
	"CargoNet_01_box_F",
	"Land_FoodSacks_01_cargo_white_idap_F",
	"Land_FoodSacks_01_cargo_brown_idap_F",
	"Land_FoodSacks_01_cargo_brown_F",
	"Box_IND_AmmoVeh_F",
	"Box_East_AmmoVeh_F",
	"Box_NATO_AmmoVeh_F",
	"Box_AAF_Uniforms_F",
	"Box_CSAT_Uniforms_F",
	"Box_NATO_Uniforms_F",
	"Box_IDAP_Uniforms_F",
	"Land_Ammobox_rounds_F",
	"Box_GEN_Equip_F",
	"Box_AAF_Equip_F",
	"Box_CSAT_Equip_F",
	"Box_NATO_Equip_F",
	"Box_IDAP_Equip_F",
	"Land_MetalCase_01_large_F",
	"Box_IND_Support_F",
	"Box_East_Support_F",
	"Box_NATO_Support_F",
	"Box_IND_Grenades_F",
	"Box_East_Grenades_F",
	"Box_NATO_Grenades_F",
	"Box_IND_AmmoOrd_F",
	"Box_East_AmmoOrd_F",
	"Box_NATO_AmmoOrd_F",
	"Box_IDAP_AmmoOrd_F",
	"Box_IED_Exp_F",
	"Box_IND_Ammo_F",
	"Box_East_Ammo_F",
	"Box_NATO_Ammo_F",
	"Box_T_East_Ammo_F",
	"Box_Syndicate_Ammo_F",
	"Box_IND_Wps_F",
	"Box_East_Wps_F",
	"Box_NATO_Wps_F",
	"Box_T_East_Wps_F",
	"Box_Exile_Weapons_1v",
	"Box_T_NATO_Wps_F",

//From "All in Arma"
	"guerillacacheBox",
	"rubasicammunitionBox",
	"ammoBox_pmc",
	"czbasicweapons_ep1",
	"gerbasicweapons_ep1",
	"guerillacacheBox_ep1",
	"tkbasicammunitionBox_ep1",
	"tkbasicweapons_ep1",
	"tklaunchers_ep1",
	"tkspecialweapons_ep1",
	"unbasicammunitionBox_ep1",
	"unbasicweapons_ep1",
	"usbasicammunitionBox_ep1",
	"usbasicweapons_ep1",
	"uslaunchers_ep1",
	"usspecialweapons_ep1",
	"usbasicammunitionBox"
];
