R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
/*
//From "All in Arma"
	"land_misc_cargo1a_ep1",
	"land_misc_cargo1ao",
	"land_misc_cargo1ao_ep1",
	"land_misc_cargo1b",
	"land_misc_cargo1b_ep1",
	"land_misc_cargo1bo",
	"land_misc_cargo1c",
	"land_misc_cargo1c_ep1",
	"land_misc_cargo1d",
	"land_misc_cargo1d_ep1",
	"land_misc_cargo1e",
	"land_misc_cargo1e_ep1",
	"land_misc_cargo1f",
	"land_misc_cargo1g",
	"land_misc_cargomarket1a_ep1",
	"base_warfarebcontructionsite",
	"misc_cargo_cont_net1",
	"misc_cargo_cont_small",
	"misc_cargo_cont_small2"
*/	
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
/*
//From "All in Arma"
	["land_misc_cargo1ao", 110],
	["land_misc_cargo1a_ep1", 110],
	["land_misc_cargo1ao_ep1", 110],
	["land_misc_cargo1b", 110],
	["land_misc_cargo1b_ep1", 110],
	["land_misc_cargo1bo", 110],
	["land_misc_cargo1c", 110],
	["land_misc_cargo1c_ep1", 110],
	["land_misc_cargo1d", 110],
	["land_misc_cargo1d_ep1", 110],
	["land_misc_cargo1e", 110],
	["land_misc_cargo1e_ep1", 110],
	["land_misc_cargo1f", 110],
	["land_misc_cargo1g", 110],
	["land_misc_cargomarket1a_ep1", 110],
	["base_warfarebcontructionsite", 110],
	["fortress2", 20],
	["warfarebcamp", 30],
	["misc_cargo_cont_small", 65],
	["misc_cargo_cont_small2", 50]
*/	
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
/*
//From A3_Vanilla
	["camping_base_f", 1],
	["flagsmall_f", 1],
	["hbarrier_base_f", 3],
	["land_hbarriertower_f", 8],
	["land_hbarrierwall6_f", 4],
	["land_hbarrierwall_corridor_f", 4],
	["land_hbarrier_1_f", 1],
	["land_hbarrier_3_f", 2],
	["helper_base_f", 1],
	["helih", 1],
	["land_portablelight_single_f", 1],
	["land_metalbarrel_empty_f", 2],
	["land_campfire_f", 1],
	["land_fireplace_f", 1],
	["land_obstacle_bridge_f", 2],
	["land_razorwire_f", 2],
	["land_sign_mines_f", 1],
	["land_pallet_milboxes_f", 5],
	["land_paperbox_closed_f", 5],
	["land_paperbox_open_empty_f", 5],
	["land_paperbox_open_full_f", 5],
	["land_bargate_f", 2],
	["land_cncbarriermedium4_f", 6],
	["land_cncbarriermedium_f", 2],
	["land_cncbarrier_f", 2],
	["land_cncbarrier_stripes_f", 2],
	["land_cncwall1_f", 2],
	["land_cncwall4_f", 6],
	["land_mil_concretewall_f", 2],
	["land_shoot_house_wall_f", 2],
	["sign_f", 2],
	["signad_sponsors_f", 1],
	["shelter_base_f", 2],
	["land_plasticbarrier_01_f", 2],
	["land_plasticbarrier_02_f", 2],
	["bagbunker_base_f", 15],
	["land_bagbunker_small_f", 6],
	["bagfence_base_f", 2],
	["flagcarriercore", 2],

//From "All in Arma"
	["concrete_wall_ep1", 3],
	["fencewood", 1],
	["fencewoodpalet", 1],
	["wire", 2],
	["fire", 1],
	["flagcarriersmall", 1],
	["fort_razorwire", 2],
	["gunrack1", 2],
	["base_warfarebbarrier5x", 3],
	["base_warfarebbarrier10x", 6],
	["base_warfarebbarrier10xtall", 12],
	["base_warfarebbarrier5xpreview", 2],
	["land_camonet_east", 2],
	["land_camonet_nato", 2],
	["land_fire", 1],
	["land_fire_barrel", 3],
	["land_fort_watchtower", 20],
	["land_guardshed", 3],
	["land_misc_cargo1ao", 120],
	["land_misc_cargo1a_ep1", 120],
	["land_misc_cargo1ao_ep1", 120],
	["land_misc_cargo1b", 120],
	["land_misc_cargo1b_ep1", 120],
	["land_misc_cargo1bo", 120],
	["land_misc_cargo1c", 120],
	["land_misc_cargo1c_ep1", 120],
	["land_misc_cargo1d", 120],
	["land_misc_cargo1d_ep1", 120],
	["land_misc_cargo1e", 120],
	["land_misc_cargo1e_ep1", 120],
	["land_misc_cargo1f", 120],
	["land_misc_cargo1g", 120],
	["land_misc_cargomarket1a_ep1", 120],
	["land_woodenramp", 2],
	["land_fort_bagfence_corner", 3],
	["land_fort_bagfence_long", 2],
	["land_fort_bagfence_round", 4],
	["land_fort_rampart", 4],
	["land_fortified_nest_big", 20],
	["land_fortified_nest_small", 10],
	["land_cncblock", 2],
	["land_cncblock_d", 2],
	["land_cncblock_stripes", 2],
	["land_hbarrier_large", 4],
	["land_bagfencecorner", 2],
	["land_hbarrier1", 1],
	["land_hbarrier3", 2],
	["land_hbarrier5", 3],
	["land_toilet", 3],
	["paletabase", 2],
	["roadbarrier_light", 2],
	["targettraining", 2],
	["warfarebunkersign", 3],
	["zavoraanim", 2],
	["base_warfarebcontructionsite", 120],
	["fortress1", 10],
	["hedgehog", 3],
	["land_prebehlavka", 3],
	["land_prolejzacka", 2],
	["ammocrate_nointeractive_", 7],
	["misc_cargo_cont_net1", 25],
	["misc_cargo_cont_small", 75],
	["misc_cargo_cont_small2", 60],
	["shed", 2],
	["target", 2]
*/
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
/*
//From A3_Vanilla
	"camping_base_f",
	"flagsmall_f",
	"hbarrier_base_f",
	"helper_base_f",
	"helih",
	"land_portablelight_single_f",
	"land_metalbarrel_empty_f",
	"land_campfire_f",
	"land_fireplace_f",
	"land_obstacle_bridge_f",
	"land_razorwire_f",
	"land_sign_mines_f",
	"land_pallet_milboxes_f",
	"land_paperbox_closed_f",
	"land_paperbox_open_empty_f",
	"land_paperbox_open_full_f",
	"land_bargate_f",
	"land_cncbarriermedium4_f",
	"land_cncbarriermedium_f",
	"land_cncbarrier_f",
	"land_cncbarrier_stripes_f",
	"land_cncwall1_f",
	"land_cncwall4_f",
	"land_mil_concretewall_f",
	"land_shoot_house_wall_f",
	"sign_f",
	"land_plasticbarrier_01_f",
	"land_plasticbarrier_02_f",
	"bagbunker_base_f",
	"bagfence_base_f",
	"flagcarriercore",

//From "All in Arma"
	"concrete_wall_ep1",
	"fencewood",
	"fencewoodpalet",
	"wire",
	"fire",
	"flagcarriersmall",
	"fort_razorwire",
	"gunrack1",
	"base_warfarebbarrier5x",
	"land_camonet_east",
	"land_camonet_nato",
	"land_fire",
	"land_fort_watchtower",
	"land_guardshed",
	"land_woodenramp",
	"land_fort_bagfence_corner",
	"land_fort_bagfence_long",
	"land_fort_bagfence_round",
	"land_fort_rampart",
	"land_fortified_nest_big",
	"land_fortified_nest_small",
	"land_cncblock",
	"land_cncblock_d",
	"land_cncblock_stripes",
	"land_hbarrier_large",
	"land_bagfencecorner",
	"land_toilet",
	"paletabase",
	"roadbarrier_light",
	"targettraining",
	"warfarebunkersign",
	"zavoraanim",
	"fortress1",
	"hedgehog",
	"land_prebehlavka",
	"land_prolejzacka",
	"ammocrate_nointeractive_",
	"misc_cargo_cont_net1",
	"shed",
	"target"
*/	
];