//	Sniper Rifles 
		"bnae_falkor_blk_virtual",
		"bnae_falkor_snd_virtual",
		"bnae_falkor_camo1_virtual",
		"bnae_falkor_camo2_virtual",
		"bnae_mk1_virtual",
		"bnae_mk1_t_virtual",
		"bnae_mk1_t_camo1_virtual",
		"bnae_trg42_virtual",
		"bnae_trg42_camo1_virtual",
		"bnae_trg42_camo2_virtual",
		"bnae_trg42_mmrs_virtual",
		"bnae_trg42_mmrs_camo1_virtual",
		"bnae_trg42_f_mmrs_virtual",
		"bnae_trg42_f_camo1_virtual",
		"bnae_trg42_f_virtual",
		"bnae_trg42_f_mmrs_camo1_virtual",
