// BSF_Client_GetRandomQuote

private _quote = "";

_quoteArray = [
	"The trouble is, you think you have time.",
	"Man is the only creature who refuses to be what he is.",
	"Silence is as deep as eternity, speech a shallow as time.",
	"You don’t drown by falling in the water. You drown by staying there.",
	"Conscience doth make cowards of us all.",
	"People do not lack strength the lack will.",
	"Sometimes a cigar is just a cigar.",
	"You will not be punished for your anger; your anger will punish you.",
	"What worries you masters you.",
	"When you look into an abyss, the abyss also looks into you.",
	"We don’t see things as they are; we see them as we are.",
	"One must be deeply aware of the impermanence of the world.",
	"The opinion is the medium between knowledge and ignorance.",
	"If a man who cannot count finds a four-leaf clover, is he lucky?",
	"Remember your humanity, and forget the rest.",
	"Beauty may be skin deep, but ugly goes clear to the bone.",
	"To be sane in a world of madmen is in itself madness.",
	"Once you hear the details of victory, it is hard to distinguish it from a defeat.",
	"All great truths begin as blasphemies.",
	"If the world was blind, how many people would you impress?",
	"Before you embark on a journey of revenge, dig two graves.",
	"People with opinions just go around bothering each other.",
	"Anyone can hold the helm when the sea is calm.",
	"The solution to every problem is another problem.",
	"The more you sweat in peace, the less you bleed in war.",
	"The two most powerful warriors are patience and time.",
	"Older men declare war. But it is the youth that must fight and die.",
	"In peace, sons bury their fathers. In war, fathers bury their sons.",
	"It is well that war is so terrible, otherwise we should grow too fond of it.",
	"Only the dead have seen the end of the war.",
	"When the rich wage war, it's the poor who die.",
	"You can no more win a war than you can win an earthquake.",
	"War does not determine who is right - only who is left.",
	"The supreme art of war is to subdue the enemy without fighting.",
	"There is no instance of a nation benefitting from prolonged warfare.",
	"War is the science of destruction.",
	"The first casualty when war comes is truth.",
	"The best weapon against an enemy is another enemy.", 
	"War is fear cloaked in courage.",
	"A man can die but once.",
	"The evil that men do lives after them; The good is oft interred with their bones.",
	"There is nothing either good or bad, but thinking makes it so.",
	"I am one who loved not wisely but too well.",
	"Et tu, Brute?",
	"Misery acquaints a man with strange bedfellows.",
	"Cowards die many times before their deaths; the valiant never taste of death but once.",
	"The better part of valor is discretion.",
	"We know what we are, but know not what we may be.",
	"There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.",
	"The miserable have no other medicine, but only hope.",
	"A horse! a horse! my kingdom for a horse!",
	"Now is the winter of our discontent.",
	"Cry “havoc!” and let slip the dogs of war.	",
	"Lord, what fools these mortals be!",
	"My dull brain was wrought with things forgotten.",
	"At this hour... lie at my mercy all mine enemies.",
	"The axe forgets, but the tree remembers.",
	"Even a man who is pure of heart may harbor darkness unknown.",
	"Not all scars are visible, nor all wounds healed.",
	"In darkness, truth whispers louder.",
	"Time is a river that erodes even the sharpest stone.",
	"The soul always knows what to do to heal itself. The challenge is to silence the mind.",
	"To carry a burden unseen is the heaviest weight of all.",
	"Even shadows must be cast by light.",
	"You either die a hero, or live long enough to see yourself become the villain.",
	"The deeper the sorrow, the less tongue it hath.",
	"He who opens a school door, closes a prison.",
	"Sometimes silence is the most powerful scream.",
	"Every man has his secret sorrows which the world knows not.",
	"The dead don’t haunt the living; guilt does.",
	"Pain is inevitable. Suffering is optional.",
	"Beware the man who has nothing left to lose.",
	"What you run from owns you. What you face makes you free.",
	"We fear monsters because we are still haunted by our own reflection.",
	"Nothing haunts us like the things we didn’t say.",
	"The grave is the final critic.",
	"Hope is the last thing ever lost.",
	"You are not defeated when you fall. You are defeated when you refuse to rise.",
	"To understand death, you must first understand life.",
	"Do not seek the light; become it.",
	"A man's true enemy is himself.",
	"We wear masks not to hide, but to survive.",
	"Not every cage has bars.",
	"There is no courage without fear.",
	"The past is a ghost that never stops knocking.",
	"Sometimes, the hardest battles are fought in silence.",
	"A war within leaves no visible wounds.",
	"Men become the stories they tell.",
	"Only the broken can see beauty in ruins.",
	"It is better to be hated for what you are than loved for what you are not.",
	"Justice is what love looks like in public.",
	"Those who hunt monsters must be careful not to become them.",
	"The price of truth is often betrayal.",
	"There is comfort in routine, but no growth.",
	"Trust is built in drops and lost in buckets.",
	"No man crosses the same river twice.",
	"Fear does not stop death. It stops life.",
	"Power reveals the man, not the mask.",
	"A soul without purpose will seek its own end.",
	"Even the stars are born from chaos.",
	"The fire that warms can also consume.",
	"Not all who wander are lost, but some are running.",
	"Sometimes, survival is the most radical act.",
	"In forgetting, we find peace."
];

_quote = selectRandom _quoteArray;

_quote;