// ExileServer_BS2_loadCrate.sqf

if (!isServer) exitWith {};

private ["_loot","_depthModifier","_actualCount", "_actualAdditionalCount", "_chance", "_class", "_count", "_crate", "_enableCrateFillDebug", "_minCount", "_possibleAdditionalCount", "_wreckId"];

_wreckId = _this select 0;
_crate = _this select 1;
_enableCrateFillDebug = _this select 2;

_loot = [];
_depthModifier = (getPosASL _crate select 2) * -0.01;

_riflesCount =		[5,8,12];   // min,mean,max
_pistolsCount =		[4,8,12];
_miscItemsCount =	[3,6,8];
_snipersCount =		[2,4,6];
_ammoCount =		[10,10,30];
_uniformsCount =	[1,2,5];
_backpacksCount =	[2,3,5];
_vestsCount =		[2,3,5];
_headgearCount =	[2,3,5];
_basePartsCount =	[2,4,6];
_medicalCount =		[4,6,8];
_foodCount =		[3,4,5];

_miscItemsArray = [
["Exile_Item_BeefParts",1],
["Exile_Item_Laptop",1],
["Exile_Item_BaseCameraKit",1],
["Exile_Item_CodeLock",1],
["Exile_Item_Matches",1],
["Exile_Item_CookingPot",1],
["Exile_Item_CanOpener",1],
["Exile_Item_Handsaw",1],
["Exile_Item_Pliers",1],
["Exile_Item_Grinder",1],
["Exile_Item_Foolbo",1],
["Exile_Melee_SledgeHammer",1],
["Exile_Melee_Axe",1],
["Exile_Item_Shovel",1],
["Exile_Item_Wrench",1],
["Exile_Item_ToiletPaper",1],
["NVGoggles",1],
["Exile_Item_DuctTape",2],
["Exile_Item_ExtensionCord",1],
["Exile_Item_FuelCanisterEmpty",1],
["Exile_Item_JunkMetal",3],
["Exile_Item_LightBulb",1],
["Exile_Item_MetalBoard",2],
["Exile_Item_MetalPole",2],
["Exile_Item_SafeKit",1],
["Exile_Item_MetalScrews",5],
["Exile_Item_MetalWire",3],
["Exile_Item_Cement",4],
["Exile_Item_Sand",4],
["Exile_Item_Rope",2]
];

_riflesArray = [
["rhs_weap_m4_mstock",1],
["rhs_weap_m4a1_mstock",1],
["rhs_weap_m4a1_d_mstock",1],
["rhs_weap_m4a1_blockII_bk",1],
["rhs_weap_m4a1_blockII_M203_bk",1],
["rhs_weap_m4a1_blockII_KAC_bk",1],
["rhs_weap_m27iar",1],
["rhs_weap_m27iar_grip",1],
["rhs_weap_vhsd2",1],
["rhs_weap_vhsd2_bg",1],
["rhs_weap_vhsd2_ct15",1],
["rhs_weap_vhsd2_bg_ct15",1],
["rhs_weap_vhsk2",1],			
["arifle_Katiba_C_F",1],
["arifle_Mk20_F",1],
["arifle_MX_GL_F",1],
["rhs_weap_g36c",1],
["rhs_weap_g36kv",1],
["rhs_weap_savz58v_rail_fold_black",1],
["rhs_weap_savz58v_rail_black",1],
["rhs_weap_savz58p_rail_black",1],
["rhs_weap_savz58v_fold_black",1],
["rhs_weap_savz58v_black",1],
["rhs_weap_savz58p_black",1],
["rhs_weap_savz58v_ris_fold",1],
["rhs_weap_savz58v_ris",1],
["rhs_weap_savz58v_rail_fold",1],
["rhs_weap_savz58v_rail",1],
["rhs_weap_savz58p_rail",1],
["rhs_weap_savz58v_fold",1],
["rhs_weap_savz58v",1],
["rhs_weap_savz58p",1],
["rhs_weap_akm",1],
["rhs_weap_aks74",1],
["rhs_weap_aks74u",1],
["rhs_weap_aks74un",1],
["rhs_weap_aks74n_2",1],
["rhs_weap_aks74n",1],
["rhs_weap_aks74_2",1],
["rhs_weap_akms",1],
["rhs_weap_akmn",1],
["rhs_weap_ak74m_plummag",1],			
["rhs_weap_akm_zenitco01_b33",1],
["rhs_weap_ak74m_camo_folded",1],
["rhs_weap_ak74m_folded",1],
["rhs_weap_ak74m_plummag_folded",1],
["rhs_weap_ak74m_desert_folded",1],
["rhs_weap_ak74m_2mag_camo",1],
["rhs_weap_ak74m_2mag",1],
["rhs_weap_ak74n_2",1],
["rhs_weap_ak74n",1],
["rhs_weap_ak74mr",1],
["rhs_weap_ak74m_fullplum",1],
["rhs_weap_ak74m_zenitco01",1],
["rhs_weap_ak74m_zenitco01_b33",1],
["rhs_weap_ak74m_desert",1],
["rhs_weap_ak74m_camo",1],
["rhs_weap_ak74m",1],
["rhs_weap_ak105_zenitco01_b33",1],
["rhs_weap_ak105_zenitco01",1],
["rhs_weap_ak105",1],
["rhs_weap_ak104_zenitco01_b33",1],
["rhs_weap_ak104_zenitco01",1],
["rhs_weap_ak104",1],
["rhs_weap_ak103_zenitco01_b33",1],
["rhs_weap_ak103_zenitco01",1],
["rhs_weap_ak103_2",1],
["rhs_weap_ak103_1",1],
["rhs_weap_ak103",1],
["rhs_weap_mk18_KAC_wd",1],
["rhs_weap_mk18_KAC_d",1],
["rhs_weap_mk18_KAC_bk",1],
["rhs_weap_mk18_KAC",1],
["rhs_weap_mk18_wd",1],
["rhs_weap_mk18_d",1],
["rhs_weap_mk18_bk",1],
["rhs_weap_mk18",1],
["rhs_weap_m4a1_blockII_KAC_wd",1],
["rhs_weap_m4a1_blockII_KAC_d",1],
["rhs_weap_m4a1_blockII_KAC",1],
["rhs_weap_m4a1_blockII_wd",1],
["rhs_weap_m4a1_blockII_d",1],
["rhs_weap_m4a1_blockII",1],
["rhs_weap_m4a1_pmag",1],
["rhs_weap_m4a1_wd_mstock",1],
["rhs_weap_m4a1_wd",1],
["rhs_weap_m4a1_d",1],
["rhs_weap_m4a1",1],
["rhs_weap_m4_pmag",1],
["rhs_weap_m4",1],
["rhs_weap_m16a4_pmag",1],
["rhs_weap_m16a4",1],
["rhs_weap_hk416d145_wd_2",1],
["rhs_weap_hk416d145_wd",1],
["rhs_weap_hk416d145_d_2",1],
["rhs_weap_hk416d145_d",1],
["rhs_weap_hk416d145",1],
["rhs_weap_hk416d10_LMT_wd",1],
["rhs_weap_hk416d10_LMT_d",1],
["rhs_weap_hk416d10_LMT",1],
["rhs_weap_hk416d10",1],
["rhs_weap_m4_m203S",1],
["rhs_weap_m4a1_m203s",1],
["rhs_weap_m4a1_m203s_d",1],
["rhs_weap_m4a1_m203s_wd",1],
["rhs_weap_m4a1_m203s_sa",1],
["rhs_weap_hk416d10_m320",1],
["rhs_weap_hk416d145_m320",1],
["rhs_weap_m4_m320",1],
["rhs_weap_g36kv_ag36",1],
["rhs_weap_aks74n_gp25",1],
["rhs_weap_aks74_gp25",1],
["rhs_weap_akms_gp25",1],
["rhs_weap_akm_gp25",1],
["rhs_weap_akmn_gp25",1],			
["rhs_weap_ak74mr_gp25",1],
["rhs_weap_ak74n_gp25",1],
["rhs_weap_ak74m_fullplum_gp25",1],
["rhs_weap_ak74m_gp25",1],
["rhs_weap_ak103_gp25",1],
["rhs_weap_mk18_m320",1],
["rhs_weap_m4_m203",1],
["rhs_weap_m4a1_blockII_M203_wd",1],			
["rhs_weap_m4a1_blockII_M203_d",1],
["rhs_weap_m4a1_blockII_M203",1],
["rhs_weap_m4a1_m320",1],
["rhs_weap_m4a1_m203",1],
["rhs_weap_m38_rail",1],
["rhs_weap_m38",1],
["rhs_weap_m70ab2",1],
["rhs_weap_m240B",1],
["rhs_weap_m240B_CAP",1],
["rhs_weap_m240G",1],
["rhs_weap_pkm",1],
["rhs_weap_pkp",1],
["arifle_MX_SW_Black_F",1],
["arifle_MX_SW_F",1],
["LMG_Mk200_F",1],
["rhs_weap_mg42",1],
["rhs_weap_m84",1],
["rhs_weap_m1garand_sa43",1],
["rhs_weap_MP44",1],
["rhs_weap_kar98k",1]
];

_pistolsArray = [
["hgun_Pistol_heavy_02_F",1],
["hgun_ACPC2_F",1],
["hgun_P07_F",1],
["rhs_weap_cz99_etched",1],
["rhs_weap_cz99",1],
["rhs_weap_type94_new",1],
["rhs_weap_tt33",1],
["rhs_weap_6p53",1],
["rhs_weap_M320",1],
["rhsusf_weap_m9",1],
["rhsusf_weap_glock17g4",1],
["rhs_weap_savz61_folded",1],
["rhsusf_weap_MP7A1_aor1",1],
["rhsusf_weap_MP7A1_desert",1],
["rhsusf_weap_MP7A1_winter",1],
["rhs_weap_pp2000_folded",1]
];

_snipersArray = [ 
["rhs_weap_vss",1],
["rhs_weap_asval",1],
["rhs_weap_asval_folded",1],
["rhs_weap_sr25",1],
["rhs_weap_sr25_d",1],
["rhs_weap_sr25_wd",1],
["rhs_weap_sr25_ec",1],
["rhs_weap_sr25_ec_d",1],
["rhs_weap_sr25_ec_wd",1],
["rhs_weap_mk17_CQC",1],
["rhs_weap_mk17_STD",1],
["rhs_weap_mk17_LB",1],
["rhs_weap_mk17_CQC_Folded",1],
["rhs_weap_mk17_STD_Folded",1],
["rhs_weap_mk17_LB_Folded",1],
["rhs_weap_m76",1],
["rhs_weap_svds",1],
["rhs_weap_svdp_wd",1],
["rhs_weap_svdp",1],
["rhs_weap_svd",1],
["rhs_weap_m110",1],
["rhs_weap_m14ebrri",1],
["rhs_weap_m14_d",1],
["rhs_weap_m14_wd",1],
["rhs_weap_m14_rail_d",1],
["rhs_weap_m14_ris_d",1],
["rhs_weap_m14_rail_wd",1],
["rhs_weap_m14_ris_wd",1],
["rhs_weap_m14_rail_fiberglass",1],
["rhs_weap_m14_ris_fiberglass",1],
["rhs_weap_m14_fiberglass",1],
["rhs_weap_m14_rail",1],
["rhs_weap_m14_ris",1],
["rhs_weap_m14",1],
["rhs_weap_m70b1n",1],
["rhs_weap_m70ab2_fold",1],
["rhs_weap_m70b1",1],
["rhs_weap_m21a",1],
["rhs_weap_m21a_pbg40",1],
["rhs_weap_m21a_pr",1],
["rhs_weap_m21a_pr_pbg40",1],
["rhs_weap_m21s",1],
["rhs_weap_m21s_pr",1],
["rhs_weap_m21a_fold",1],
["rhs_weap_m21s_fold",1],
["rhs_weap_m92_fold",1],
["rhs_weap_m92",1],
["arifle_MXM_Black_F",1],
["srifle_DMR_02_camo_F",1],
["srifle_DMR_05_hex_F",1],
["rhs_weap_mosin_sbr",1],
["rhs_weap_dsr1",1],
["rhs_weap_M107",1],
["rhs_weap_M107_d",1],
["rhs_weap_M107_w",1],
["rhs_weap_XM2010_sa",1],
["rhs_weap_XM2010_d",1],
["rhs_weap_XM2010_wd",1],
["rhs_weap_XM2010",1],
["rhs_weap_m40a5",1],
["rhs_weap_m40a5_d",1],
["rhs_weap_m40a5_wd",1],
["rhs_weap_m24sws",1],
["rhs_weap_m24sws_d",1],
["rhs_weap_m24sws_wd",1],
["rhs_weap_m24sws_blk",1],
["rhs_weap_m24sws_ghillie",1],
["rhs_weap_m82a1",1],
["rhs_weap_t00",1]
];

_ammoArray = [
["9Rnd_45ACP_Mag",3],
["16Rnd_9x21_Mag",3],
["30Rnd_9x21_Mag",3],
["11Rnd_45ACP_Mag",3],
["rhs_10rnd_9x39mm_SP5",3],
["rhs_20rnd_9x39mm_SP5",3],
["rhsusf_mag_7x45acp_MHP",3],
["rhs_18rnd_9x21mm_7BT3",3],
["rhs_18rnd_9x21mm_7N29",3],
["rhs_18rnd_9x21mm_7N28",3],
["rhsusf_mag_17Rnd_9x19_JHP",3],
["rhssaf_mag_15Rnd_9x19_FMJ",3],
["rhs_mag_9x19mm_7n31_44",3],
["rhs_mag_9x19_17",3],
["rhs_mag_9x18_12_57N181S",3],
["rhs_mag_9x18_8_57N181S",3],
["rhsusf_mag_40Rnd_46x30_FMJ",3],
["rhsgref_8Rnd_762x63_M2B_M1rifle",3],
["rhsusf_8Rnd_Slug",3],
["rhsusf_8Rnd_00Buck",3],
["rhsusf_5Rnd_Slug",3],
["rhsusf_5Rnd_00Buck",3],
["rhs_mag_20Rnd_556x45_M200_Stanag",3],
["rhs_mag_20Rnd_762x51_m61_fnfal",3],
["rhsusf_20Rnd_762x51_m80_Mag",3],
["rhs_mag_20Rnd_SCAR_762x51_m61_ap",3],
["rhs_mag_20Rnd_SCAR_762x51_m80_ball",3],
["rhsgref_20rnd_765x17_vz61",3],
["rhsgref_30rnd_1143x23_M1911B_SMG",3],
["rhsgref_30Rnd_792x33_SmE_StG",3],
["rhs_mag_30Rnd_762x51_m61_fnfal",3],
["30Rnd_556x45_Stanag",3],
["30Rnd_65x39_caseless_green",3],
["30Rnd_65x39_caseless_khaki_mag",3],
["30Rnd_65x39_caseless_black_mag",3],
["30Rnd_65x39_caseless_mag",3],
["30Rnd_762x39_AK12_Mag_F",3],
["rhs_mag_6x8mm_mhp",3],
["30Rnd_545x39_Mag_F",3],
["rhs_30Rnd_545x39_AK",3],
["rhs_45Rnd_545X39_AK",3],
["rhs_60Rnd_545x39_7N10_AK",3],
["30Rnd_580x42_Mag_F",3],
["10Rnd_Mk14_762x51_Mag",3],
["20Rnd_762x51_Mag",3],
["10Rnd_762x54_Mag",3],
["rhs_30Rnd_762x39mm",3],
["rhs_30Rnd_762x39mm_Savz58",3],
["rhssaf_30Rnd_762x39mm_M67",3],
["rhs_75Rnd_762x39mm",3],
["75Rnd_762x39_Mag_F",3],
["rhs_100Rnd_762x54mmR",3],
["rhs_10Rnd_762x54mmR_7N1",3],
["rhs_5Rnd_338lapua_t00",3],
["rhssaf_30rnd_556x45_EPR_G36",3],
["rhsgref_30rnd_556x45_m21",3],
["rhs_mag_30Rnd_556x45_M855_PMAG_Tan",3],
["rhs_mag_30Rnd_556x45_M855_PMAG",3],
["rhs_mag_30Rnd_556x45_M855_Stanag",3],
["rhsusf_Rnd_762x51",3],
["rhsgref_Rnd_792x57_SmE_drum",3],
["100Rnd_65x39_caseless_black_mag",3],
["100Rnd_65x39_caseless_khaki_mag",3],
["100Rnd_65x39_caseless_mag",3],
["100Rnd_580x42_Mag_F",3],
["rhsusf_100Rnd_762x51",3],
["rhs_mag_100Rnd_556x45_Mk262_cmag",3],
["rhsusf_100Rnd_556x45_soft_pouch",3],
["rhssaf_100rnd_556x45_EPR_G36",3],
["1Rnd_556x45_Drum_Sand_Mag_F",3],
["1Rnd_762x51_Bo",3],
["1Rnd_762x54_Bo",3],
["rhs_200rnd_556x45_B_SAW",3],
["rhsusf_200Rnd_556x45_bo",3],
["rhsusf_200Rnd_556x45_soft_pouch",3],
["200Rnd_556x45_Box_F",3],
["200Rnd_65x39_cased_Bo",3],
["rhssaf_2Rnd_762x54R",3],
["100Rnd_mas_HMMWV_762x51_Stanag",3],
["rhsgref_296Rnd_792x57_SmE_belt",3],
["rhsgref_5Rnd_792x57_kar98k",3],
["rhsgref_10Rnd_792x57_m76",3],
["rhsgref_5Rnd_762x54_m38",3],
["rhsusf_10Rnd_762x51_m62_Mag",3],
["rhsusf_5Rnd_762x51_AICS_m62_Mag",3],
["rhs_10Rnd_762x39mm_U",3],
["rhs_10Rnd_762x39mm_tracer",3],
["rhs_mag_762x25_8",3],
["rhs_10Rnd_762x39mm",3],
["rhsusf_mag_10Rnd_STD_BMG_M33",3],
["rhsusf_5Rnd_300winmag_xm2010",3],
["BSF_12g_Drum_32Rnnd_Slug",3],
["BSF_12g_Drum_32Rnnd_Pellets",3],
["Exile_Magazine_5Rnd_127x108_APDS_KSVK",3],
["5Rnd_APDS_338LM_Magazine",3],
["7Rnd_408_Mag",3],
["5Rnd_127x108_Mag",3],
["10Rnd_127x54_Mag",3],
["Exile_Magazine_10Rnd_127x99_m107",3],
["130Rnd_338_Mag",3],
["1Rnd_93x64_Mag",3],
["10Rnd_93x64_DMR_05_Mag",3]
];

_uniformsArray = [ 
["U_O_SpecopsUniform_ocamo",1],
["U_O_SpecopsUniform_blk",1],
["U_B_SpecopsUniform_sgg",1],
["U_I_E_Uniform_01_F",1],
["U_I_E_Uniform_01_tanktop_F",1],
["U_I_E_Uniform_01_shortsleeve_F",1],
["U_I_E_Uniform_01_sweater_F",1],
["U_I_E_Uniform_01_officer_F",1],
["U_B_CombatUniform_vest_mcam_wdl_f",1],
["BSF_Combat_Uniform_1_Multi2",1],
["BSF_Combat_Uniform_1_Tiger",1],
["BSF_Combat_Uniform_1_Arid",1],
["BSF_Viper_Winter",1],
["U_B_T_Soldier_F",1],
["U_I_E_CBRN_Suit_01_EAF_F",1],
["U_I_CBRN_Suit_01_AAF_F",1],
["U_B_CBRN_Suit_01_Wdl_F",1],
["U_B_CBRN_Suit_01_Tropic_F",1],
["U_B_CBRN_Suit_01_MTP_F",1],
["U_C_CBRN_Suit_01_White_F",1],
["U_C_CBRN_Suit_01_Blue_F",1],
["U_I_E_Uniform_01_coveralls_F",1],
["U_O_R_Gorka_01_camo_F",1],
["U_O_R_Gorka_01_brown_F",1],
["U_O_R_Gorka_01_F",1],
["U_B_CombatUniform_tshirt_mcam_wdL_f",1],
["U_B_CombatUniform_mcam_wdl_f",1],
["U_I_L_Uniform_01_deserter_F",1],
["U_I_L_Uniform_01_camo_F",1],
["U_I_C_Soldier_Bandit_5_F",1],
["U_I_C_Soldier_Bandit_4_F",1],
["U_I_C_Soldier_Bandit_3_F",1],
["U_I_C_Soldier_Bandit_2_F",1],
["U_I_C_Soldier_Camo_F",1],
["U_B_CTRG_Soldier_urb_1_F",1],
["U_B_CTRG_Soldier_urb_2_F",1],
["U_B_CTRG_Soldier_urb_3_F",1],
["U_I_C_Soldier_Bandit_1_F",1],
["U_I_C_Soldier_Para_5_F",1],
["U_I_C_Soldier_Para_4_F",1],
["U_I_C_Soldier_Para_3_F",1],
["U_I_C_Soldier_Para_2_F",1],
["U_I_C_Soldier_Para_1_F",1],
["U_O_V_Soldier_Viper_hex_F",1],
["U_O_V_Soldier_Viper_F",1],
["U_O_T_FullGhillie_tna_F",1],
["U_O_T_Sniper_F",1],
["U_O_T_Officer_F",1],
["U_O_T_Soldier_F",1],
["U_B_GEN_Commander_F",1],
["U_B_GEN_Soldier_F",1],
["U_B_CTRG_Soldier_3_F",1],
["U_B_CTRG_Soldier_2_F",1],
["U_B_CTRG_Soldier_F",1],
["U_B_T_FullGhillie_tna_F",1],
["U_B_T_Sniper_F",1],
["U_B_T_Soldier_SL_F",1],
["U_B_T_Soldier_AR_F",1],
["U_B_CTRG_Soldier_3_arid_F",1],
["U_B_CTRG_Soldier_arid_F",1],
["U_B_CTRG_Soldier_2_arid_F",1]
];

_backpacksArray = [ 
["BSF_Viper_Black",1],
["BSF_Bergen_Black_F",1],
["BSF_Bergen_Winter_F",1],
["BSF_Bergen_Winter2_F",1],
["BSF_Bergen_BlackDigi_F",1],
["BSF_Bergen_Carbon_F",1],
["BSF_Bergen_MossyOak_F",1],
["BSF_Bergen_Tiger_F",1],
["BSF_Bergen_WD_F",1],
["BSF_Bergen_Desert_F",1],
["U_O_V_Soldier_Viper_F",1],
["U_O_V_Soldier_Viper_F",1],
["U_O_V_Soldier_Viper_hex_F",1],
["BSF_Caryyall_Winter_F",1],
["BSF_Caryyall_Black_F",1],
["BSF_Caryyall_Carbon_F",1],
["BSF_Caryyall_Arid_F",1],
["BSF_Caryyall_Multi2_F",1],
["BSF_Caryyall_Tiger_F",1],
["BSF_ViperHarness_Black_F",1],
["BSF_ViperHarness_Winter_F",1],
["BSF_ViperLightHarness_Black_F",1],
["BSF_ViperLightHarness_Winter_F",1],
["B_ViperLightHarness_oli_F",1],
["B_ViperLightHarness_khk_F",1],
["B_ViperLightHarness_hex_F",1],
["B_ViperLightHarness_ghex_F",1],
["B_ViperLightHarness_blk_F",1],
["B_ViperHarness_oli_F",1],
["B_ViperHarness_khk_F",1],
["B_ViperHarness_hex_F",1],
["B_ViperHarness_ghex_F",1],
["B_ViperHarness_blk_F",1]
];

_vestsArray = [
["V_PlateCarrierGL_wdl",1],
["V_PlateCarrierGL_rgr",1],
["V_PlateCarrierGL_wdl",1],
["V_PlateCarrier1_wdl",1],
["V_PlateCarrier2_wdl",1],
["V_PlateCarrierSpec_wdl",1],
["V_PlateCarrierGL_rgr",1],
["V_PlateCarrier2_rgr",1],
["V_PlateCarrier3_rgr",1],
["V_PlateCarrier1_rgr_noflag_F",1],
["V_PlateCarrier2_rgr_noflag_F",1],
["V_PlateCarrier1_rgr",1],
["V_PlateCarrierSpec_rgr",1],
["V_PlateCarrierIAGL_oli",1],
["V_CarrierRigKBT_01_olive_F",1],
["V_CarrierRigKBT_01_EAF_F",1],
["V_PlateCarrierGL_mtp",1],		
["V_PlateCarrierSpec_mtp",1],
["V_PlateCarrierIAGL_dgtl",1],
["V_PlateCarrierIA2_dgtl",1],
["V_PlateCarrierIA1_dgtl",1],
["V_PlateCarrierGL_mtp",1],			
["V_PlateCarrierGL_tna_F",1],		
["V_PlateCarrierGL_blk",1],
["V_PlateCarrierSpec_blk",1],
["V_PlateCarrier1_blk ",1],
["V_PlateCarrier2_blk",1],
["V_PlateCarrierGL_blk ",1],
["BSF_Plate_Carrier_GL_Winter",1],
["BSF_Plate_Carrier_GL_Arid",1],
["BSF_Plate_Carrier_GL_Tiger",1],
["BSF_Plate_Carrier_GL_Carbon",1],
["BSF_Plate_Carrier_GL_Multi01",1],
["BSF_Plate_Carrier_GL_Multi02",1],
["V_CarrierRigKBT_01_heavy_EAF_F",1],
["V_CarrierRigKBT_01_heavy_olive_F",1],
["V_PlateCarrier_Kerry ",1],
["V_SmershVest_01_radio_F",1],
["V_SmershVest_01_F",1],
["V_PlateCarrierH_CTRG",1],
["V_PlateCarrierL_CTRG",1]
];

_headgearArray = [
["BSF_Stealth_Helmet_Carbon",1],
["BSF_Stealth_Helmet_Multi2",1],
["BSF_Stealth_Helmet_Arid",1],
["BSF_Stealth_Helmet_Tiger",1],
["BSF_Stealth_Helmet_Winter",1],
["BSF_Stealth_Helmet_Police",1],
["H_HelmetO_ViperSP_ghex_F",1],
["H_HelmetO_ViperSP_hex_F",1],
["H_HelmetSpecO_blk",1],
["H_HelmetSpecO_ocamo",1],
["H_HelmetSpecO_ghex_F",1],
["H_HelmetLeaderO_ghex_F",1],
["Exile_Headgear_GasMask",1]
];

_basePartsArray = [
["BSF_IronWall_Low_Kit",1],
["BSF_IronWall_Post_Kit",1],
["BSF_IronWall_Tri_Kit",1],
["BSF_IronWall_Tri_Low_Kit",1],
["BSF_IronWall_WindowOpening_Tri_Kit",1],
["BSF_IronWall_Window_Tri_Kit",1],
["BSF_IronWall_DoorOpening_Tri_Kit",1],
["BSF_IronWall_Door_Tri_Kit",1],
["BSF_IronWall_Topper_Kit",1],
["BSF_IronWall_DoorOpening_C_Kit",1],
["BSF_IronWall_DoorOpening_L_Kit",1],
["BSF_IronWall_DoorOpening_R_Kit",1],
["BSF_IronWall_Door_C_Kit",1],
["BSF_IronWall_Door_L_Kit",1],
["BSF_IronWall_Door_R_Kit",1],
["BSF_IronWall_WindowOpening_C_Kit",1],
["BSF_IronWall_WindowOpening_L_Kit",1],
["BSF_IronWall_WindowOpening_R_Kit",1],
["BSF_IronWall_Window_C_Kit",1],
["BSF_IronWall_Window_L_Kit",1],
["BSF_IronWall_Window_R_Kit",1],
["BSF_IronWall_Floor_Basic_Kit",1],
["BSF_IronWall_Floor_Half_Kit",1],
["BSF_IronWall_Floor_Tri_Kit",1],
["BSF_IronWall_Stairport_Kit",1],
["BSF_IronWall_Floorport_Kit",1],
["BSF_IronWall_Floorport_Door_Kit",1],
["BSF_IronWall_StairRail_L_Kit",1],
["BSF_IronWall_StairRail_R_Kit",1],
["BSF_IronWall_Stairs_2_C_Kit",1],
["BSF_IronWall_Roof_Kit",1],
["BSF_IronWall_Roof_Corner_Kit",1],
["BSF_IronWall_Roof_Tri_Kit",1],
["BSF_IronWall_Stairs_Ext_C_Kit",1],
["BSF_IronWall_Stairs_Ext_L_Kit",1],
["BSF_IronWall_Stairs_Ext_R_Kit",1],
["BSF_IronWall_Gate_1L_Kit",1],
["BSF_IronWall_Gate_1R_Kit",1],
["BSF_Helipad_01_Kit",1],
["BSF_IronWall_Round_Kit",1],
["BSF_IronWall_Round_Low_Kit",1],
["BSF_IronWall_Half_Kit",1],
["BSF_IronWall_Tri_Topper_Kit",1],
["BSF_IronWall_Floor_Round_Kit",1],
["BSF_IronWall_Round_Topper_Kit",1],
["BSF_IronWall_Stairs_RoofTop_Kit",1],
["BSF_IronWall_Roof_Half_Kit",1],
["BSF_IronWall_Roof_Corner_Full_Kit",1],
["BSF_IronWall_Roof_Round_Kit",1], 
["BSF_IronWall_Floor_Quarter_Kit",1],
["BSF_IronWall_WindowOpening_Round_Kit",1],
["BSF_IronWall_Window_Round_Kit",1],
["BSF_IronWall_2_Low_Kit",1],
["BSF_IronWall_2_Tri_Kit",1],
["BSF_IronWall_2_Tri_Low_Kit",1],
["BSF_IronWall_2_WindowOpening_Tri_Kit",1],
["BSF_IronWall_2_Window_Tri_Kit",1],
["BSF_IronWall_2_DoorOpening_Tri_Kit",1],
["BSF_IronWall_2_Door_Tri_Kit",1],
["BSF_IronWall_2_DoorOpening_C_Kit",1],
["BSF_IronWall_2_DoorOpening_L_Kit",1],
["BSF_IronWall_2_DoorOpening_R_Kit",1],
["BSF_IronWall_2_Door_C_Kit",1],
["BSF_IronWall_2_Door_L_Kit",1],
["BSF_IronWall_2_Door_R_Kit",1],
["BSF_IronWall_2_WindowOpening_C_Kit",1],
["BSF_IronWall_2_WindowOpening_L_Kit",1],
["BSF_IronWall_2_WindowOpening_R_Kit",1],
["BSF_IronWall_2_Window_C_Kit",1],
["BSF_IronWall_2_Window_L_Kit",1],
["BSF_IronWall_2_Window_R_Kit",1],
["BSF_IronWall_Stairs_2_L_Kit",1],
["BSF_IronWall_Stairs_2_R_Kit",1],
["BSF_IronWall_2_Half_Kit",1],
["BSF_IronWall_2_Round_Kit",1],
["BSF_IronWall_2_Round_Low_Kit",1],
["BSF_IronWall_2_WindowOpening_Round_Kit",1],
["BSF_IronWall_2_Window_Round_Kit",1],
["BSF_IronWall_Basic_Kit",1],
["BSF_IronWall_Third_Kit",1],
["BSF_IronWall_2_Basic_Kit",1],
["BSF_IronWall_2_Third_Kit",1],
["BSF_CastleWall_Basic_Kit",1],
["BSF_CastleWall_Low_Kit",1],
["BSF_CastleWall_Round_Kit",1],
["BSF_CastleWall_Round_Low_Kit",1],
["BSF_CastleWall_Tri_Kit",1],
["BSF_CastleWall_Tri_Low_Kit",1],
["BSF_CastleWall_Half_Kit",1],
["BSF_CastleWall_Third_Kit",1],
["BSF_GreenWall_Basic_Kit",1],
["BSF_GreenWall_Low_Kit",1],
["BSF_GreenWall_Topper_Kit",1],
["BSF_GreenWall_Round_Kit",1],
["BSF_GreenWall_Round_Low_Kit",1],
["BSF_GreenWall_Round_Topper_Kit",1],
["BSF_GreenWall_Tri_Kit",1],
["BSF_GreenWall_Tri_Low_Kit",1],
["BSF_GreenWall_Tri_Topper_Kit",1],
["BSF_GreenWall_Half_Kit",1],
["BSF_GreenWall_Third_Kit",1],
["BSF_GreenWall_Post_Kit",1],
["BSF_StoneWall_Basic_Kit",1],
["BSF_StoneWall_Low_Kit",1],
["BSF_StoneWall_Round_Kit",1],
["BSF_StoneWall_Round_Low_Kit",1],
["BSF_StoneWall_Tri_Kit",1],
["BSF_StoneWall_Tri_Low_Kit",1],
["BSF_StoneWall_Half_Kit",1],
["BSF_StoneWall_Third_Kit",1],
["BSF_WoodWall_Basic_Kit",1],
["BSF_WoodWall_Low_Kit",1],
["BSF_WoodWall_Topper_Kit",1],
["BSF_WoodWall_Round_Kit",1],
["BSF_WoodWall_Round_Low_Kit",1],
["BSF_WoodWall_Round_Topper_Kit",1],
["BSF_WoodWall_Tri_Kit",1],
["BSF_WoodWall_Tri_Low_Kit",1],
["BSF_WoodWall_Tri_Topper_Kit",1],
["BSF_WoodWall_Half_Kit",1],
["BSF_WoodWall_Third_Kit",1],
["BSF_WoodWall_Post_Kit",1],
["BSF_IronWall_DoorOpening_Round_Kit",1],
["BSF_IronWall_Door_Round_Kit",1],
["BSF_IronWall_2_DoorOpening_Round_Kit",1],
["BSF_IronWall_2_Door_Round_Kit",1],
["BSF_CastleWall_DoorOpening_C_Kit",1],
["BSF_CastleWall_DoorOpening_L_Kit",1],
["BSF_CastleWall_DoorOpening_R_Kit",1],
["BSF_CastleWall_DoorOpening_Round_Kit",1],
["BSF_CastleWall_DoorOpening_Tri_Kit",1],
["BSF_CastleWall_Door_C_Kit",1],
["BSF_CastleWall_Door_L_Kit",1],
["BSF_CastleWall_Door_R_Kit",1],
["BSF_CastleWall_Door_Round_Kit",1],
["BSF_CastleWall_Door_Tri_Kit",1],
["BSF_GreenWall_DoorOpening_C_Kit",1],
["BSF_GreenWall_DoorOpening_L_Kit",1],
["BSF_GreenWall_DoorOpening_R_Kit",1],
["BSF_GreenWall_DoorOpening_Round_Kit",1],
["BSF_GreenWall_DoorOpening_Tri_Kit",1],
["BSF_GreenWall_Door_C_Kit",1],
["BSF_GreenWall_Door_L_Kit",1],
["BSF_GreenWall_Door_R_Kit",1],
["BSF_GreenWall_Door_Round_Kit",1],
["BSF_GreenWall_Door_Tri_Kit",1],
["BSF_StoneWall_DoorOpening_C_Kit",1],
["BSF_StoneWall_DoorOpening_L_Kit",1],
["BSF_StoneWall_DoorOpening_R_Kit",1],
["BSF_StoneWall_DoorOpening_Round_Kit",1],
["BSF_StoneWall_DoorOpening_Tri_Kit",1],
["BSF_StoneWall_Door_C_Kit",1],
["BSF_StoneWall_Door_L_Kit",1],
["BSF_StoneWall_Door_R_Kit",1],
["BSF_StoneWall_Door_Round_Kit",1],
["BSF_StoneWall_Door_Tri_Kit",1],
["BSF_WoodWall_DoorOpening_C_Kit",1],
["BSF_WoodWall_DoorOpening_L_Kit",1],
["BSF_WoodWall_DoorOpening_R_Kit",1],
["BSF_WoodWall_DoorOpening_Round_Kit",1],
["BSF_WoodWall_DoorOpening_Tri_Kit",1],
["BSF_WoodWall_Door_C_Kit",1],
["BSF_WoodWall_Door_L_Kit",1],
["BSF_WoodWall_Door_R_Kit",1],
["BSF_WoodWall_Door_Round_Kit",1],
["BSF_WoodWall_Door_Tri_Kit",1],
["BSF_CastleWall_WindowOpening_C_Kit",1],
["BSF_CastleWall_WindowOpening_L_Kit",1],
["BSF_CastleWall_WindowOpening_R_Kit",1],
["BSF_CastleWall_WindowOpening_Round_Kit",1],
["BSF_CastleWall_WindowOpening_Tri_Kit",1],
["BSF_CastleWall_Window_C_Kit",1],
["BSF_CastleWall_Window_L_Kit",1],
["BSF_CastleWall_Window_R_Kit",1],
["BSF_CastleWall_Window_Round_Kit",1],
["BSF_CastleWall_Window_Tri_Kit",1],
["BSF_GreenWall_WindowOpening_C_Kit",1],
["BSF_GreenWall_WindowOpening_L_Kit",1],
["BSF_GreenWall_WindowOpening_R_Kit",1],
["BSF_GreenWall_WindowOpening_Round_Kit",1],
["BSF_GreenWall_WindowOpening_Tri_Kit",1],
["BSF_GreenWall_Window_C_Kit",1],
["BSF_GreenWall_Window_L_Kit",1],
["BSF_GreenWall_Window_R_Kit",1],
["BSF_GreenWall_Window_Round_Kit",1],
["BSF_GreenWall_Window_Tri_Kit",1],
["BSF_StoneWall_WindowOpening_C_Kit",1],
["BSF_StoneWall_WindowOpening_L_Kit",1],
["BSF_StoneWall_WindowOpening_R_Kit",1],
["BSF_StoneWall_WindowOpening_Round_Kit",1],
["BSF_StoneWall_WindowOpening_Tri_Kit",1],
["BSF_StoneWall_Window_C_Kit",1],
["BSF_StoneWall_Window_L_Kit",1],
["BSF_StoneWall_Window_R_Kit",1],
["BSF_StoneWall_Window_Round_Kit",1],
["BSF_StoneWall_Window_Tri_Kit",1],
["BSF_WoodWall_WindowOpening_C_Kit",1],
["BSF_WoodWall_WindowOpening_L_Kit",1],
["BSF_WoodWall_WindowOpening_R_Kit",1],
["BSF_WoodWall_WindowOpening_Round_Kit",1],
["BSF_WoodWall_WindowOpening_Tri_Kit",1],
["BSF_WoodWall_Window_C_Kit",1],
["BSF_WoodWall_Window_L_Kit",1],
["BSF_WoodWall_Window_R_Kit",1],
["BSF_WoodWall_Window_Round_Kit",1],
["BSF_WoodWall_Window_Tri_Kit",1],
["BSF_IronWall_Floor_Hatchport_Kit",1],
["BSF_IronWall_Floor_Hatch_Kit",1],
["BSF_CastleWall_Floor_Kit",1],
["BSF_CastleWall_Floor_Round_Kit",1],
["BSF_CastleWall_Floor_Tri_Kit",1],
["BSF_CastleWall_Floor_Half_Kit",1],
["BSF_CastleWall_Floor_Quarter_Kit",1],
["BSF_CastleWall_Floor_Hatchport_Kit",1],
["BSF_CastleWall_Floor_Hatch_Kit",1],
["BSF_CastleWall_Floorport_Kit",1],
["BSF_CastleWall_Floorport_Door_Kit",1],
["BSF_CastleWall_Stairport_Kit",1],
["BSF_GreenWall_Floor_Kit",1],
["BSF_GreenWall_Floor_Round_Kit",1],
["BSF_GreenWall_Floor_Tri_Kit",1],
["BSF_GreenWall_Floor_Half_Kit",1],
["BSF_GreenWall_Floor_Quarter_Kit",1],
["BSF_GreenWall_Floor_Hatchport_Kit",1],
["BSF_GreenWall_Floor_Hatch_Kit",1],
["BSF_GreenWall_Floorport_Kit",1],
["BSF_GreenWall_Floorport_Door_Kit",1],
["BSF_GreenWall_Stairport_Kit",1],
["BSF_StoneWall_Floor_Kit",1],
["BSF_StoneWall_Floor_Round_Kit",1],
["BSF_StoneWall_Floor_Tri_Kit",1],
["BSF_StoneWall_Floor_Half_Kit",1],
["BSF_StoneWall_Floor_Quarter_Kit",1],
["BSF_StoneWall_Floor_Hatchport_Kit",1],
["BSF_StoneWall_Floor_Hatch_Kit",1],
["BSF_StoneWall_Floorport_Kit",1],
["BSF_StoneWall_Floorport_Door_Kit",1],
["BSF_StoneWall_Stairport_Kit",1],
["BSF_WoodWall_Floor_Kit",1],
["BSF_WoodWall_Floor_Round_Kit",1],
["BSF_WoodWall_Floor_Tri_Kit",1],
["BSF_WoodWall_Floor_Half_Kit",1],
["BSF_WoodWall_Floor_Quarter_Kit",1],
["BSF_WoodWall_Floor_Hatchport_Kit",1],
["BSF_WoodWall_Floor_Hatch_Kit",1],
["BSF_WoodWall_Floorport_Kit",1],
["BSF_WoodWall_Floorport_Door_Kit",1],
["BSF_WoodWall_Stairport_Kit",1],
["BSF_IronWall_Roof_Square_Kit",1],
["BSF_IronWall_Roof_Third_Kit",1],
["BSF_CastleWall_Roof_Kit",1],
["BSF_CastleWall_Roof_Square_Kit",1],
["BSF_CastleWall_Roof_Half_Kit",1],
["BSF_CastleWall_Roof_Third_Kit",1],
["BSF_CastleWall_Roof_Corner_Kit",1],
["BSF_CastleWall_Roof_Corner_Full_Kit",1],
["BSF_CastleWall_Roof_Round_Kit",1],
["BSF_CastleWall_Roof_Tri_Kit",1],
["BSF_GreenWall_Roof_Kit",1],
["BSF_GreenWall_Roof_Square_Kit",1],
["BSF_GreenWall_Roof_Half_Kit",1],
["BSF_GreenWall_Roof_Third_Kit",1],
["BSF_GreenWall_Roof_Corner_Kit",1],
["BSF_GreenWall_Roof_Corner_Full_Kit",1],
["BSF_GreenWall_Roof_Round_Kit",1],
["BSF_GreenWall_Roof_Tri_Kit",1], 
["BSF_CastleWall_Stairs_L_Kit",1],
["BSF_CastleWall_Stairs_R_Kit",1],
["BSF_IronWall_Stairs_Spiral_2_L_Kit",1],
["BSF_IronWall_Stairs_Spiral_2_R_Kit",1],
["BSF_GreenWall_StairRail_L_Kit",1],
["BSF_GreenWall_StairRail_R_Kit",1],
["BSF_GreenWall_Stairs_2_C_Kit",1],
["BSF_GreenWall_Stairs_2_L_Kit",1],
["BSF_GreenWall_Stairs_2_R_Kit",1],
["BSF_GreenWall_Stairs_RoofTop_Kit",1],
["BSF_GreenWall_Stairs_Ext_C_Kit",1],
["BSF_GreenWall_Stairs_Ext_L_Kit",1],
["BSF_GreenWall_Stairs_Ext_R_Kit",1],
["BSF_GreenWall_Stairs_Spiral_2_L_Kit",1],
["BSF_GreenWall_Stairs_Spiral_2_R_Kit",1],
["BSF_WoodWall_StairRail_L_Kit",1],
["BSF_WoodWall_StairRail_R_Kit",1],
["BSF_WoodWall_Stairs_2_C_Kit",1],
["BSF_WoodWall_Stairs_2_L_Kit",1],
["BSF_WoodWall_Stairs_2_R_Kit",1],
["BSF_WoodWall_Stairs_RoofTop_Kit",1],
["BSF_WoodWall_Stairs_Ext_C_Kit",1],
["BSF_WoodWall_Stairs_Ext_L_Kit",1],
["BSF_WoodWall_Stairs_Ext_R_Kit",1],
["BSF_WoodWall_Stairs_Spiral_1_L_Kit",1],
["BSF_WoodWall_Stairs_Spiral_1_R_Kit",1],
["BSF_CastleWall_Gate_1L_Kit",1],
["BSF_CastleWall_Gate_1R_Kit",1],
["BSF_GreenWall_Gate_1L_Kit",1],
["BSF_GreenWall_Gate_1R_Kit",1],
["Exile_Item_ConcreteFloorKit",1],
["Exile_Item_ConcreteWindowKit",1],
["Exile_Item_ConcreteDoorKit",1],
["Exile_Item_ConcreteDoorwayKit",1],
["Exile_Item_ConcreteFloorPortKit",1],
["Exile_Item_ConcreteFloorPortSmallKit",1],
["Exile_Item_ConcreteGateKit",1],
["Exile_Item_ConcreteStairsKit",1],
["Exile_Item_ConcreteSupportKit",1],
["Exile_Item_ConcreteWallKit",1],
["Exile_Item_FloodLightKit",1]
];

_medicalArray = [
["Exile_Item_Defibrillator",1],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_InstaDoc",3],
["Exile_Item_Bandage",3],
["Exile_Item_Vishpirin",2],
["rzinfection_antivirus_injector",2],
["rzinfection_antivirus_pills",1],
["BSF_WaterPure_Tabs",2],
["BSF_Item_Banndage_Used",1],
["BSF_Item_Poison",1],
["BSF_Antibiotics",1],
["BSF_Item_IV_Bag_Used",1],
["BSF_IV_Bag",1],
["BSF_Item_Disinfectant_Spray",1],
["BSF_Item_Blood_Bag_Clean",2],
["BSF_Item_Blood_Bag_KR",1],
["BSF_Item_Pain_Killlers",1],
["BSF_Item_Vitamins1",1]
];

_foodArray = [
["Exile_Item_EMRE",3],
["Exile_Item_GloriousKnakworst",1],
["Exile_Item_GloriousKnakworst_Cooked",1],
["Exile_Item_Surstromming",1],
["Exile_Item_Surstromming_Cooked",1],
["Exile_Item_SausageGravy",1],
["Exile_Item_SausageGravy_Cooked",1],
["Exile_Item_Catfood",1],
["Exile_Item_Catfood_Cooked",1],
["Exile_Item_ChristmasTinner",1],
["Exile_Item_ChristmasTinner_Cooked",1],
["Exile_Item_BBQSandwich",1],
["Exile_Item_BBQSandwich_Cooked",1],
["Exile_Item_DsNuts",1],
["Exile_Item_CockONut",1],
["Exile_Item_MacasCheese",1],
["Exile_Item_MacasCheese_Cooked",1],
["Exile_Item_Dogfood",1],
["Exile_Item_Dogfood_Cooked",1],
["Exile_Item_Cheathas",1],
["Exile_Item_Noodles",1],
["Exile_Item_SeedAstics",1],
["Exile_Item_Raisins",1],
["Exile_Item_Moobar",1],
["Exile_Item_InstantCoffee",1],
["Exile_Item_SheepSteak_Cooked",1],
["Exile_Item_AlsatianSteak_Cooked",1],
["Exile_Item_CatSharkFilet_Cooked",1],
["Exile_Item_FinSteak_Cooked",1],
["Exile_Item_GoatSteak_Cooked",1],
["Exile_Item_TurtleFilet_Cooked",1],
["Exile_Item_TunaFilet_Cooked",1],
["Exile_Item_RabbitSteak_Cooked",1],
["Exile_Item_ChickenFilet_Cooked",1],
["Exile_Item_RoosterFilet_Cooked",1],
["Exile_Item_MulletFilet_Cooked",1],
["Exile_Item_SalemaFilet_Cooked",1],
["Exile_Item_MackerelFilet_Cooked",1],
["Exile_Item_OrnateFilet_Cooked",1],
["Exile_Item_SnakeFilet_Cooked",1],
["Exile_Item_PlasticBottleCoffee",2],
["Exile_Item_PowerDrink",2],
["Exile_Item_PlasticBottleFreshWater",1],
["Exile_Item_Beer",1],
["Exile_Item_EnergyDrink",1],
["Exile_Item_ChocolateMilk",1],
["Exile_Item_MountainDupe",1],
["Exile_Item_PlasticBottleEmpty",1]
];

_rifles = round (random _riflesCount * _depthModifier);
	while {_rifles > 0} do {
	_loot pushBack selectRandom _riflesArray;
	_rifles = _rifles -1;
};

_pistols = round (random _pistolsCount * _depthModifier);
	while {_pistols > 0} do {
	_loot pushBack selectRandom _pistolsArray;
	_pistols = _pistols -1;
};

_miscItems = round (random _miscItemsCount * _depthModifier);
	while {_miscItems > 0} do {
	_loot pushBack selectRandom _miscItemsArray;
	_miscItems = _miscItems -1;
};

_snipers = round (random _snipersCount * _depthModifier);
	while {_snipers > 0} do {
	_loot pushBack selectRandom _snipersArray;
	_snipers = _snipers -1;
};

_ammo = round (random _ammoCount * _depthModifier);
	while {_ammo > 0} do {
	_loot pushBack selectRandom _ammoArray;
	_ammo = _ammo -1;
};

_uniforms = round (random _uniformsCount * _depthModifier);
	while {_uniforms > 0} do {
	_loot pushBack selectRandom _uniformsArray;
	_uniforms = _uniforms -1;
};

_backpacks = round (random _backpacksCount * _depthModifier);
	while {_backpacks > 0} do {
	_loot pushBack selectRandom _backpacksArray;
	_backpacks = _backpacks -1;
};

_vests = round (random _vestsCount * _depthModifier);
	while {_vests > 0} do {
	_loot pushBack selectRandom _vestsArray;
	_vests = _vests -1;
};

_headgear = round (random _headgearCount * _depthModifier);
	while {_headgear > 0} do {
	_loot pushBack selectRandom _headgearArray;
	_headgear = _headgear -1;
};

_baseParts = round (random _basePartsCount * _depthModifier);
	while {_baseParts > 0} do {
	_loot pushBack selectRandom _basePartsArray;
	_baseParts = _baseParts -1;
};

_medical = round (random _medicalCount * _depthModifier);
	while {_medical > 0} do {
	_loot pushBack selectRandom _medicalArray;
	_medical = _medical -1;
};

_food = round (random _foodCount * _depthModifier);
	while {_food > 0} do {
	_loot pushBack selectRandom _foodArray;
	_food = _food -1;
};

{ 
    _crate addItemCargoGlobal _x; 
} 
forEach _loot;
